// Code generated by tools/contractgen from api/openapi.json. DO NOT EDIT.
// Source of truth: api/openapi.json (the versioned HTTP contract).
// Readonly by convention: every emitted member is readonly.
// HTTP surface SHA-256: 4e79b247e53e96296d4a47047bd621565df9e91287bd3f6a73e9916429ff4ce9

export interface AccountDeletionCancelRequest {
  readonly reason?: string;
}

export interface AccountDeletionRequest {
  readonly canceled_at: string | null;
  readonly executed_at: string | null;
  readonly requested_at: string;
  readonly status: "requested" | "executed" | "canceled";
}

export interface ArenaArgumentForm {
  readonly attempt: string;
  readonly content: string;
  readonly csrf_token: string;
  readonly relation: "support" | "oppose" | "context";
}

export interface ArenaAttributionForm {
  readonly argument_ids: ReadonlyArray<string>;
  readonly change_id: string;
  readonly csrf_token: string;
}

export interface ArenaDraftRequest {
  readonly category: "technology" | "science" | "philosophy" | "politics" | "economics" | "health" | "culture" | "society";
  readonly context?: string;
  readonly language: "pt-BR" | "en-US";
  readonly statement: string;
}

export interface ArenaDraftUpdateRequest {
  readonly category: "technology" | "science" | "philosophy" | "politics" | "economics" | "health" | "culture" | "society";
  readonly context?: string;
  readonly expected_version: number;
  readonly language: "pt-BR" | "en-US";
  readonly statement: string;
}

export interface ArenaExport {
  readonly arena: PublicArena;
  readonly arguments: ArenaExportArgumentPage;
  readonly influence: ArenaExportInfluence;
  readonly positions: ArenaExportPositions;
  readonly schema_version: number;
}

export interface ArenaExportArgument {
  readonly content: string | null;
  readonly created_at: string;
  readonly id: string;
  readonly influence: ArenaExportArgumentInfluence;
  readonly parent_id: string | null;
  readonly relation: "support" | "oppose" | "context";
  readonly sources: ReadonlyArray<ArgumentSource>;
  readonly status: "published" | "withdrawn";
  readonly withdrawn_at: string | null;
}

export interface ArenaExportArgumentInfluence {
  readonly distinct_people: number;
  readonly valid_attributions: number;
}

export interface ArenaExportArgumentPage {
  readonly items: ReadonlyArray<ArenaExportArgument>;
  readonly next_cursor: string | null;
}

export interface ArenaExportInfluence {
  readonly influenced_authors: number;
  readonly valid_attributions: number;
}

export interface ArenaExportPositions {
  readonly current: PositionDistribution;
  readonly initial: PositionDistribution;
  readonly participants_total: number;
  readonly position_changes: number;
  readonly suppressed: boolean;
}

export interface ArenaFeed {
  readonly items: ReadonlyArray<PublicArenaSummary>;
  readonly next_cursor: string | null;
}

export interface ArenaPassHistory {
  readonly items: ReadonlyArray<ArenaPassHistoryEntry>;
  readonly next_cursor: string | null;
}

export interface ArenaPassHistoryEntry {
  readonly arena_id: string;
  readonly consumed_at: string;
  readonly consumption_id: string;
  readonly origin: "PURCHASE" | "MEMBER" | "ADMIN";
  readonly reference: string;
}

export interface ArenaPassLot {
  readonly created_at: string;
  readonly expired: boolean;
  readonly expires_at: string | null;
  readonly origin: "PURCHASE" | "MEMBER" | "ADMIN";
  readonly quantity: number;
  readonly remaining: number;
}

export interface ArenaPassSummary {
  readonly available_total: number;
  readonly checked_at: string;
  readonly lots: ReadonlyArray<ArenaPassLot>;
}

export interface ArenaPositionForm {
  readonly csrf_token: string;
  readonly position: "agree" | "disagree" | "undecided";
}

export interface Argument {
  readonly arena_id: string;
  readonly content: string | null;
  readonly created_at: string;
  readonly id: string;
  readonly parent_id: string | null;
  readonly relation: "support" | "oppose" | "context";
  readonly status: "published" | "withdrawn";
}

export interface ArgumentAttributionMetrics {
  readonly checked_at: string;
  readonly distinct_people: number;
  readonly valid_attributions: number;
}

export interface ArgumentListItem {
  readonly arena_id: string;
  readonly content: string | null;
  readonly created_at: string;
  readonly id: string;
  readonly parent_id: string | null;
  readonly relation: "support" | "oppose" | "context";
  readonly reply_count: number;
  readonly status: "published" | "withdrawn";
}

export interface ArgumentMutationResult {
  readonly argument: Argument;
  readonly replayed: boolean;
}

export interface ArgumentPage {
  readonly items: ReadonlyArray<ArgumentListItem>;
  readonly next_cursor: string | null;
}

export interface ArgumentPublishRequest {
  readonly content: string;
  readonly relation: "support" | "oppose" | "context";
  readonly sources?: ReadonlyArray<ArgumentSource>;
}

export interface ArgumentSource {
  readonly description?: string;
  readonly url: string;
}

export interface AttributionRecordRequest {
  readonly argument_ids: ReadonlyArray<string>;
}

export interface AttributionRecordResult {
  readonly argument_ids: ReadonlyArray<string>;
  readonly replayed: boolean;
}

export interface AttributionSignal {
  readonly changes?: number;
  readonly counterpart_id: string;
  readonly dominant_events?: number;
  readonly kind: "reciprocity" | "concentration" | "rapid_alternation";
  readonly mutual_events?: number;
  readonly reversals?: number;
  readonly share_basis_points?: number;
}

export interface AttributionSignals {
  readonly author_id: string;
  readonly checked_at: string;
  readonly policy_version: string;
  readonly signals: ReadonlyArray<AttributionSignal>;
  readonly window_seconds: number;
}

export interface AuthCodeForm {
  readonly csrf_token: string;
  readonly token: string;
}

export interface AuthLoginForm {
  readonly csrf_token: string;
  readonly email: string;
  readonly password: string;
}

export interface AuthPasswordResetForm {
  readonly csrf_token: string;
  readonly password: string;
  readonly token: string;
}

export interface AuthRecoveryRequestForm {
  readonly csrf_token: string;
  readonly email: string;
}

export interface AuthRegisterForm {
  readonly csrf_token: string;
  readonly email: string;
  readonly password: string;
}

export interface BillingCheckout {
  readonly amount_minor: number;
  readonly currency: "BRL" | "USD";
  readonly intent_id: string;
  readonly market: "BR" | "INTERNATIONAL";
  readonly product: string;
  readonly redirect_url: string;
  readonly replayed: boolean;
  readonly status: "created" | "open" | "paid" | "expired" | "failed";
}

export interface BillingCheckoutRequest {
  readonly idempotency_key: string;
  readonly market: "BR" | "INTERNATIONAL";
  readonly product: string;
}

export interface BillingPortal {
  readonly portal_url: string;
}

export interface BillingPortalRequest {
  readonly idempotency_key?: string;
}

export interface BillingSubscription {
  readonly cancel_at_period_end?: boolean;
  readonly current_period_end?: string | null;
  readonly has_subscription: boolean;
  readonly market?: "BR" | "INTERNATIONAL";
  readonly product?: string;
  readonly status?: "incomplete" | "incomplete_expired" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused";
}

export interface DeadJob {
  readonly age_seconds: number;
  readonly attempts: number;
  readonly job_id: string;
  readonly last_error_code?: string;
  readonly max_attempts: number;
  readonly retryable: boolean;
  readonly type: string;
  readonly version: number;
}

export interface DeadJobPage {
  readonly generated_at: string;
  readonly items: ReadonlyArray<DeadJob>;
  readonly total: number;
}

export interface HealthStatus {
  readonly status: "live" | "ready" | "unavailable";
}

export interface JobsQueueCounts {
  readonly dead: number;
  readonly due_now: number;
  readonly lag_seconds: number;
  readonly leased: number;
  readonly oldest_dead_seconds: number;
  readonly queued: number;
  readonly succeeded: number;
}

export interface JobsQueueHealth {
  readonly generated_at: string;
  readonly queue: JobsQueueCounts;
}

export interface JobsRetry {
  readonly job_id: string;
  readonly state: string;
  readonly type: string;
}

export interface JobsRetryRequest {
  readonly reason: string;
}

export interface LoginRequest {
  readonly email: string;
  readonly password: string;
}

export interface LoginResponse {
  readonly account_id: string;
  readonly status: "authenticated";
}

export interface MFAConfirmRequest {
  readonly code: string;
}

export interface MFAConfirmResponse {
  readonly backup_codes: ReadonlyArray<string>;
}

export interface MFAElevationResponse {
  readonly status: "elevated";
}

export interface MFAEnrollmentResponse {
  readonly secret: string;
  readonly uri: string;
}

export interface MFAVerifyRequest {
  readonly code: string;
}

export interface ModerationAppeal {
  readonly action_id: string;
  readonly appeal_id: string;
  readonly replayed: boolean;
}

export interface ModerationAppealRequest {
  readonly action_id: string;
  readonly context: string;
}

export interface ModerationCase {
  readonly case_id: string;
  readonly claimed_by?: string;
  readonly created_at: string;
  readonly priority: "low" | "normal" | "high" | "urgent";
  readonly status: "open" | "under_review" | "decided" | "closed";
  readonly target_id: string;
  readonly target_type: "arena" | "argument" | "profile";
}

export interface ModerationCasePage {
  readonly items: ReadonlyArray<ModerationCase>;
  readonly next_cursor: string | null;
}

export interface ModerationClaim {
  readonly case_id: string;
  readonly claimed_by: string;
  readonly status: string;
}

export interface ModerationDecision {
  readonly action: string;
  readonly action_id: string;
  readonly case_id: string;
}

export interface ModerationDecisionRequest {
  readonly action: "no_action" | "warning" | "link_hide" | "interaction_limit" | "argument_remove" | "arena_close" | "attribution_invalidate" | "position_invalidate" | "suspension" | "ban" | "preserve_legal";
  readonly expires_at?: string;
  readonly justification: string;
  readonly rule: string;
}

export interface ModerationReport {
  readonly rate_limited: boolean;
  readonly replayed: boolean;
  readonly report_id: string;
  readonly reports_in_window: number;
}

export interface ModerationReportRequest {
  readonly context?: string;
  readonly reason: "violence" | "doxxing" | "harassment" | "sexual" | "fraud" | "spam" | "illegal" | "evasion" | "multiaccount" | "malware" | "other";
  readonly target_id: string;
  readonly target_type: "arena" | "argument" | "profile";
}

export interface PasswordResetConfirm {
  readonly password: string;
  readonly token: string;
}

export interface PasswordResetRequest {
  readonly email: string;
}

export interface PersonalExportAccount {
  readonly created_at: string;
  readonly email: string;
  readonly email_verified: boolean;
  readonly id: string;
  readonly preferences: PersonalExportPreference | null;
  readonly profile: PersonalExportProfile | null;
  readonly sessions: ReadonlyArray<PersonalExportSession>;
  readonly status: "pending" | "active" | "suspended" | "deleted";
  readonly username_history: ReadonlyArray<PersonalExportUsername>;
}

export interface PersonalExportArenaDraft {
  readonly category: string;
  readonly context: string | null;
  readonly created_at: string;
  readonly id: string;
  readonly language: "pt-BR" | "en-US";
  readonly statement: string;
  readonly version: number;
}

export interface PersonalExportArgument {
  readonly arena_id: string;
  readonly content: string;
  readonly created_at: string;
  readonly id: string;
  readonly parent_id: string | null;
  readonly relation: "support" | "oppose" | "context";
  readonly sources: ReadonlyArray<PersonalExportSource>;
  readonly status: "published" | "withdrawn";
  readonly withdrawn_at: string | null;
}

export interface PersonalExportBilling {
  readonly checkout_intents: ReadonlyArray<PersonalExportCheckoutIntent>;
  readonly subscriptions: ReadonlyArray<PersonalExportSubscription>;
}

export interface PersonalExportCheckoutIntent {
  readonly amount_minor: number;
  readonly created_at: string;
  readonly currency: "BRL" | "USD";
  readonly market: "BR" | "INTERNATIONAL";
  readonly paid_at: string | null;
  readonly product_id: string;
  readonly status: "created" | "open" | "paid" | "expired" | "failed";
}

export interface PersonalExportDocument {
  readonly account: PersonalExportAccount;
  readonly arena_drafts: ReadonlyArray<PersonalExportArenaDraft>;
  readonly arguments: ReadonlyArray<PersonalExportArgument>;
  readonly billing: PersonalExportBilling;
  readonly excluded_categories: ReadonlyArray<"security_restricted" | "moderation_evidence" | "payment_provider_identifiers" | "antifraud_signals">;
  readonly generated_at: string;
  readonly passes: PersonalExportPasses;
  readonly position_changes: ReadonlyArray<PersonalExportPositionChange>;
  readonly positions: ReadonlyArray<PersonalExportPosition>;
  readonly schema_version: number;
  readonly wallet: PersonalExportWallet;
}

export interface PersonalExportJob {
  readonly download_token: string;
  readonly export_id: string;
  readonly status: "requested" | "ready";
}

export interface PersonalExportPassConsumption {
  readonly arena_id: string;
  readonly consumed_at: string;
}

export interface PersonalExportPassLot {
  readonly created_at: string;
  readonly expires_at: string | null;
  readonly origin: "PURCHASE" | "MEMBER" | "ADMIN";
  readonly quantity: number;
  readonly remaining: number;
}

export interface PersonalExportPasses {
  readonly consumptions: ReadonlyArray<PersonalExportPassConsumption>;
  readonly lots: ReadonlyArray<PersonalExportPassLot>;
}

export interface PersonalExportPosition {
  readonly arena_id: string;
  readonly arena_slug: string;
  readonly arena_statement: string;
  readonly created_at: string;
  readonly current_position: "agree" | "disagree" | "undecided";
  readonly initial_position: "agree" | "disagree" | "undecided";
  readonly updated_at: string;
  readonly version: number;
}

export interface PersonalExportPositionChange {
  readonly arena_id: string;
  readonly changed_at: string;
  readonly from_position: "agree" | "disagree" | "undecided";
  readonly to_position: "agree" | "disagree" | "undecided";
  readonly version: number;
}

export interface PersonalExportPreference {
  readonly marketing_opt_in: boolean;
  readonly updated_at: string;
}

export interface PersonalExportProfile {
  readonly created_at: string;
  readonly interface_locale: "pt-BR" | "en-US";
  readonly timezone: string | null;
  readonly updated_at: string;
  readonly username: string;
}

export interface PersonalExportSession {
  readonly created_at: string;
  readonly expires_at: string;
  readonly id: string;
  readonly revoked_at: string | null;
}

export interface PersonalExportSource {
  readonly description: string | null;
  readonly url: string;
}

export interface PersonalExportSubscription {
  readonly cancel_at_period_end: boolean;
  readonly created_at: string;
  readonly current_period_end: string | null;
  readonly current_period_start: string | null;
  readonly product_id: string;
  readonly status: "incomplete" | "incomplete_expired" | "trialing" | "active" | "past_due" | "canceled" | "unpaid" | "paused";
  readonly updated_at: string;
}

export interface PersonalExportUsername {
  readonly changed_at: string;
  readonly username: string;
}

export interface PersonalExportWallet {
  readonly balance_free: number;
  readonly balance_purchased: number;
  readonly transactions: ReadonlyArray<PersonalExportWalletEntry>;
}

export interface PersonalExportWalletEntry {
  readonly amount: number;
  readonly bucket: "FREE_INK" | "PURCHASED_INK";
  readonly created_at: string;
  readonly operation: string;
}

export interface PositionAggregate {
  readonly checked_at: string;
  readonly current: PositionDistribution;
  readonly initial: PositionDistribution;
  readonly participants_total: number;
  readonly suppressed: boolean;
}

export interface PositionChangeEntry {
  readonly change_id: string;
  readonly changed_at: string;
  readonly from_position: "agree" | "disagree" | "undecided";
  readonly to_position: "agree" | "disagree" | "undecided";
  readonly version: number;
}

export interface PositionChangeHistory {
  readonly items: ReadonlyArray<PositionChangeEntry>;
}

export interface PositionChangeRecord {
  readonly change_id: string;
  readonly position: PrivatePosition;
}

export interface PositionConfirmation {
  readonly position: PrivatePosition;
  readonly replayed: boolean;
}

export interface PositionDistribution {
  readonly agree: number;
  readonly disagree: number;
  readonly undecided: number;
}

export interface PositionRequest {
  readonly position: "agree" | "disagree" | "undecided";
}

export interface PrivateArena {
  readonly category: string;
  readonly closes_at?: string | null;
  readonly context?: string | null;
  readonly created_at: string;
  readonly id: string;
  readonly language: "pt-BR" | "en-US";
  readonly published_at?: string | null;
  readonly slug?: string | null;
  readonly statement: string;
  readonly status: "draft" | "published" | "closed" | "restricted" | "removed";
  readonly version: number;
}

export interface PrivateArenaList {
  readonly items: ReadonlyArray<PrivateArena>;
}

export interface PrivatePosition {
  readonly arena_id: string;
  readonly created_at: string;
  readonly current_position: "agree" | "disagree" | "undecided";
  readonly initial_position: "agree" | "disagree" | "undecided";
  readonly updated_at: string;
  readonly version: number;
}

export interface PrivateProfile {
  readonly created_at: string;
  readonly interface_locale: "pt-BR" | "en-US";
  readonly updated_at: string;
  readonly username: string;
}

export interface Problem {
  readonly code: string;
  readonly detail?: string;
  readonly request_id?: string;
  readonly status: number;
  readonly title: string;
  readonly type: string;
}

export interface ProfileReputation {
  readonly arenas: ReadonlyArray<ReputationArenaSlice>;
  readonly by_category: ReadonlyArray<ReputationDimension>;
  readonly by_language: ReadonlyArray<ReputationDimension>;
  readonly checked_at: string;
  readonly influenced_people: number;
  readonly username: string;
  readonly valid_attributions: number;
}

export interface PublicArena {
  readonly category: string;
  readonly closes_at?: string | null;
  readonly context: string | null;
  readonly id: string;
  readonly language: "pt-BR" | "en-US";
  readonly published_at: string;
  readonly slug: string;
  readonly statement: string;
  readonly status: "published" | "closed" | "restricted";
}

export interface PublicArenaSummary {
  readonly category: string;
  readonly closes_at?: string | null;
  readonly id: string;
  readonly language: "pt-BR" | "en-US";
  readonly published_at: string;
  readonly slug: string;
  readonly statement: string;
  readonly status: "published" | "closed" | "restricted";
}

export interface PublicProfile {
  readonly created_at: string;
  readonly interface_locale: "pt-BR" | "en-US";
  readonly username: string;
}

export interface RegisterRequest {
  readonly email: string;
  readonly password: string;
}

export interface RegisterResponse {
  readonly status: "pending_verification";
}

export interface ReputationArenaSlice {
  readonly arena_id: string;
  readonly category: string;
  readonly distinct_people: number;
  readonly language: "pt-BR" | "en-US";
  readonly valid_attributions: number;
}

export interface ReputationDimension {
  readonly distinct_people: number;
  readonly label: string;
  readonly valid_attributions: number;
}

export interface SearchArenaPage {
  readonly items: ReadonlyArray<SearchArenaResult>;
  readonly next_cursor: string | null;
}

export interface SearchArenaResult {
  readonly category: string;
  readonly id: string;
  readonly language: "pt-BR" | "en-US";
  readonly published_at: string;
  readonly score: number;
  readonly slug: string;
  readonly statement: string;
}

export interface SearchArgumentPage {
  readonly items: ReadonlyArray<SearchArgumentResult>;
  readonly next_cursor: string | null;
}

export interface SearchArgumentResult {
  readonly arena_id: string;
  readonly content: string;
  readonly created_at: string;
  readonly id: string;
  readonly language: "pt-BR" | "en-US";
  readonly relation: "support" | "oppose" | "context";
  readonly score: number;
}

export interface SessionListResponse {
  readonly sessions: ReadonlyArray<SessionSummary>;
}

export interface SessionRevocationRequest {
  readonly password: string;
  readonly session_id: string;
}

export interface SessionRevocationResponse {
  readonly status: "revoked";
}

export interface SessionRotationResponse {
  readonly session_id: string;
  readonly status: "rotated";
}

export interface SessionSummary {
  readonly created_at: string;
  readonly current: boolean;
  readonly expires_at: string;
  readonly id: string;
  readonly ip_address?: string;
  readonly last_seen_at: string;
  readonly user_agent?: string;
}

export interface StatusResponse {
  readonly status: string;
}

export interface TransparencyMetricCounts {
  readonly actions_recorded: number;
  readonly appeals_filed: number;
  readonly appeals_reversed: number;
  readonly arenas_closed: number;
  readonly arenas_published: number;
  readonly arenas_removed: number;
  readonly arenas_restricted: number;
  readonly arguments_published: number;
  readonly arguments_withdrawn: number;
  readonly attributions_invalidated: number;
  readonly attributions_valid: number;
  readonly eligible_accounts: number;
  readonly influenced_authors: number;
  readonly ink_admin_adjusted: number;
  readonly ink_free_consumed: number;
  readonly ink_free_expired: number;
  readonly ink_free_granted: number;
  readonly ink_purchased_consumed: number;
  readonly ink_purchased_granted: number;
  readonly ink_refunded: number;
  readonly passes_consumed: number;
  readonly passes_member_granted: number;
  readonly passes_purchase_granted: number;
  readonly position_changes: number;
  readonly reports_filed: number;
}

export interface TransparencyMetrics {
  readonly methodology_version: number;
  readonly metrics: TransparencyMetricCounts;
  readonly period_end: string;
  readonly period_start: string;
  readonly timezone: string;
  readonly updated_at: string;
}

export interface WalletBalance {
  readonly balance_free: number;
  readonly balance_purchased: number;
}

export interface WalletStatement {
  readonly items: ReadonlyArray<WalletStatementEntry>;
  readonly next_cursor: string | null;
}

export interface WalletStatementEntry {
  readonly amount: number;
  readonly bucket: "FREE_INK" | "PURCHASED_INK";
  readonly created_at: string;
  readonly operation_id: string;
  readonly operation_type: "credit_free" | "credit_member" | "credit_purchase" | "credit_refund" | "credit_admin" | "debit_argument" | "debit_admin" | "debit_refund" | "expire_free";
  readonly reference: string;
  readonly transaction_id: string;
}
