// Code generated by internal/i18ngen from locales/. DO NOT EDIT.
// Source of truth: locales/<locale>/<namespace>.json (I18N_STANDARD.md).

/** Message keys per namespace. */
export const messageKeys = {
  probe: [
    "probe.greeting",
  ] as const,
} as const;

/** Every message key across namespaces. */
export type MessageKey =
  | "probe.greeting"
;

/** Named placeholders per message key: the exact values one translation accepts. */
export const messagePlaceholders = Object.freeze({
  "probe.greeting": [],
} as const satisfies Readonly<Record<string, readonly string[]>>);

/** Localized messages per locale per key. */
export const messages: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.freeze({
  "en-US": Object.freeze({
    "probe.greeting": "Hello",
  }),
  "pt-BR": Object.freeze({
    "probe.greeting": "Olá",
  }),
});
