// Code generated by internal/i18ngen from locales/. DO NOT EDIT.
// Source of truth: locales/<locale>/<namespace>.json (I18N_STANDARD.md).

package i18n

// catalog maps locale -> message key -> localized message.
var catalog = map[string]map[string]string{
	"en-US": {
		"probe.greeting": "Hello",
	},
	"pt-BR": {
		"probe.greeting": "Olá",
	},
}

// placeholders maps message key -> sorted placeholder names.
var placeholders = map[string][]string{
	"probe.greeting": {},
}
