// Tests of the measurement: what the gate counts, where it reads the generated
// marker, and which copies it recognizes.
package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixtureValues takes every measure of one function of one fixture. The numbers
// are the contract: a fixture with thirty branches has cyclomatic 31, and the day
// the count moves is the day this test says so.
func fixtureValues(t *testing.T, fixture, function string) map[string]int {
	t.Helper()
	files, err := filepath.Glob(filepath.Join("testdata", fixture, "*.go"))
	if err != nil {
		t.Fatalf("list the fixture %s: %v", fixture, err)
	}
	if len(files) == 0 {
		t.Fatalf("the fixture %s holds no Go file", fixture)
	}
	for _, file := range files {
		source, err := os.ReadFile(file)
		if err != nil {
			t.Fatalf("read %s: %v", file, err)
		}
		positions := token.NewFileSet()
		parsed, err := parser.ParseFile(positions, file, source, parser.ParseComments)
		if err != nil {
			t.Fatalf("parse %s: %v", file, err)
		}
		for _, declaration := range parsed.Decls {
			declared, ok := declaration.(*ast.FuncDecl)
			if !ok || declared.Body == nil {
				continue
			}
			if funcName(declared) == function {
				return functionValues(positions, declared)
			}
		}
	}
	t.Fatalf("the fixture %s declares no %s", fixture, function)
	return nil
}

// TestTheMeasuresAreTheOnesDeclared pins every measure on a fixture whose shape
// a reader can count by hand.
func TestTheMeasuresAreTheOnesDeclared(t *testing.T) {
	cases := []struct {
		fixture  string
		function string
		want     map[string]int
	}{
		{
			fixture: "complex", function: "tooManyDecisions",
			// Thirty branches and one path through them.
			want: map[string]int{MetricCyclomatic: 31, MetricNesting: 1, MetricParameters: 1, MetricLines: 93, MetricStatements: 61},
		},
		{
			fixture: "nested", function: "tooDeep",
			// Five levels of nesting, and the decisions count one per level.
			want: map[string]int{MetricNesting: 5, MetricCyclomatic: 6, MetricParameters: 1, MetricLines: 18, MetricStatements: 11},
		},
		{
			fixture: "parameters", function: "tooManyParameters",
			// Eight names, which is eight parameters to the caller even though
			// the declaration groups them into one field of one type.
			want: map[string]int{MetricParameters: 8, MetricCyclomatic: 1, MetricNesting: 0, MetricLines: 3, MetricStatements: 1},
		},
		{
			fixture: "long", function: "tooLong",
			// A flat body: size is the only thing this function exceeds.
			want: map[string]int{MetricLines: 154, MetricStatements: 152, MetricCyclomatic: 1, MetricNesting: 0, MetricParameters: 1},
		},
	}
	for _, testCase := range cases {
		measured := fixtureValues(t, testCase.fixture, testCase.function)
		for metric, want := range testCase.want {
			if measured[metric] != want {
				t.Errorf("%s/%s %s = %d, want %d: the measurement moved, and every number in the baseline moved with it",
					testCase.fixture, testCase.function, metric, measured[metric], want)
			}
		}
	}
}

// TestTheFamiliesAreRefusedByTheirOwnFixtures runs the gate's own proof: every
// rule has a fixture it has to refuse, by name, and the provenance rule is
// proved in both directions.
func TestTheFamiliesAreRefusedByTheirOwnFixtures(t *testing.T) {
	withRoot(t, func() {
		if err := proveFamilies(); err != nil {
			t.Errorf("a family is no longer refused: %v", err)
		}
	})
}

// TestProvenanceIsReadWhereTheToolchainReadsIt proves the exclusion in the three
// shapes a repository actually contains: the marker before the package clause
// (excluded, even with a blank line after it, which is how sqlc writes it), the
// marker after the package clause (judged), and the marker inside a string
// (judged — the generators of this repository carry it exactly that way).
func TestProvenanceIsReadWhereTheToolchainReadsIt(t *testing.T) {
	fixtureRoot := t.TempDir()
	sources := map[string]string{
		"marked.go":   "// Code generated by sqlc. DO NOT EDIT.\n\npackage sample\n\nfunc Generated() {}\n",
		"latemark.go": "package sample\n\n// Code generated by something. DO NOT EDIT.\nfunc Later() {}\n",
		"mention.go":  "package sample\n\n// The text a generator emits, as a value.\nconst header = \"// Code generated by internal/i18ngen from locales/. DO NOT EDIT.\"\n\nfunc Judged() {}\n",
		"plain.go":    "package sample\n\nfunc Plain() {}\n",
	}
	for name, content := range sources {
		if err := os.WriteFile(filepath.Join(fixtureRoot, name), []byte(content), 0o600); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	measured, err := measureDirectory(fixtureRoot)
	if err != nil {
		t.Fatalf("measure the fixture: %v", err)
	}
	if len(measured.Generated) != 1 || filepath.Base(measured.Generated[0]) != "marked.go" {
		t.Errorf("the provenance rule excluded %v, want only marked.go", measured.Generated)
	}
	if measured.Files != 4 {
		t.Errorf("the gate read %d file(s), want the four of the fixture", measured.Files)
	}
}

// TestDuplicationFindsTheCopyAndNotTheCoincidence holds the window from both
// sides: the fixture pair is one region with two places, and a block one line
// short of the window is nothing.
func TestDuplicationFindsTheCopyAndNotTheCoincidence(t *testing.T) {
	withRoot(t, func() {
		measured, err := measureDirectory("tools/complexityaudit/testdata/duplicated")
		if err != nil {
			t.Fatalf("measure the fixture: %v", err)
		}
		regions := []finding{}
		for _, finding := range measured.Findings {
			if finding.Kind == kindDuplication {
				regions = append(regions, finding)
			}
		}
		if len(regions) != 1 {
			t.Fatalf("the fixture pair produced %d region(s), want exactly one: %+v", len(regions), regions)
		}
		if len(regions[0].Places) != 2 {
			t.Errorf("the region has %d place(s), want two (the same block with different indentation): %v", len(regions[0].Places), regions[0].Places)
		}
		if len(regions[0].Paths()) != 2 {
			t.Errorf("the region names %d file(s), want two", len(regions[0].Paths()))
		}
		if regions[0].Value < duplicationWindow {
			t.Errorf("the region is %d line(s) long and the window is %d", regions[0].Value, duplicationWindow)
		}
	})

	// The boundary, on a synthetic corpus: the same block twice, one line short
	// of the window. The lines are distinct on purpose — a corpus of identical
	// lines matches itself everywhere, which proves nothing about the window.
	short := make([]string, 0, duplicationWindow-1)
	for index := 0; index < duplicationWindow-1; index++ {
		short = append(short, fmt.Sprintf("step += value + %d", index))
	}
	lines := []dupLine{}
	for _, copy := range [][]string{short, short} {
		for _, text := range copy {
			lines = append(lines, dupLine{Path: "a.go", Line: len(lines) + 1, Text: text})
		}
	}
	if regions := duplicatedBlocks(lines); len(regions) != 0 {
		t.Errorf("a block one line short of the window was reported: %+v", regions)
	}
}

// TestTheDocumentIsOneEntryPerLine holds the writer to the format a reader
// reviews: the document parses back to what was written, and every entry is one
// line, so a tree with a hundred accepted findings is a hundred-line diff.
func TestTheDocumentIsOneEntryPerLine(t *testing.T) {
	baseline := &Baseline{
		Schema: baselineSchema,
		Note:   baselineNote,
		Entries: []Entry{
			{Kind: kindFunction, Path: "internal/wallet/application/send.go", Function: "Send", Metric: MetricCyclomatic, Value: 30, Owner: "internal/wallet/application"},
			{Kind: kindDuplication, Value: 22, Owner: "internal/arenas/application", Digest: "0eb1a6def3b63db6", Paths: []string{"internal/arenas/application/feed_cursor.go", "internal/wallet/application/statement_cursor.go"}},
		},
	}
	rendered := render(baseline)
	parsed := &Baseline{}
	if err := json.Unmarshal([]byte(rendered), parsed); err != nil {
		t.Fatalf("the rendered document does not parse: %v\n%s", err, rendered)
	}
	if len(parsed.Entries) != len(baseline.Entries) || parsed.Schema != baselineSchema || parsed.Note != baselineNote {
		t.Errorf("the document did not survive the round trip: %+v", parsed)
	}
	for _, entry := range baseline.Entries {
		encoded, err := json.Marshal(entry)
		if err != nil {
			t.Fatalf("encode the entry: %v", err)
		}
		matches := 0
		for _, line := range strings.Split(rendered, "\n") {
			if trimmed := strings.TrimSpace(line); trimmed == string(encoded) || trimmed == string(encoded)+"," {
				matches++
			}
		}
		if matches != 1 {
			t.Errorf("the entry %s occupies %d line(s), want exactly one", encoded, matches)
		}
	}
}
