// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User account records and account status lifecycle
type AppAccount struct {
	ID pgtype.UUID
	// User email address; uniqueness enforced case-insensitively via lower(email)
	Email           string
	Status          string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Account deletion state machine: requested (cooling-off, cancellable), executed or canceled; the record is retained as evidence after execution
type AppAccountDeletionRequest struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Status      string
	RequestedAt pgtype.Timestamptz
	// Instant the anonymization executed; after it the account can never authenticate again
	ExecutedAt pgtype.Timestamptz
	CanceledAt pgtype.Timestamptz
	// Holder-provided cancellation reason; restricted evidence, never part of a public projection
	CancelReason pgtype.Text
	UpdatedAt    pgtype.Timestamptz
}

// Second factor of one account: sealed TOTP secret and the last accepted time step (P16-T05)
type AppAccountMfa struct {
	AccountID pgtype.UUID
	// AES-256-GCM ciphertext (nonce || sealed secret) bound to the account identifier as AAD; no plaintext secret is ever stored
	SecretSealed []byte
	ConfirmedAt  pgtype.Timestamptz
	// Highest accepted TOTP time step; a code at or below it is refused as a replay
	LastAcceptedStep int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Minimal administrative assignments: one row per account, granted by an existing account, revocable with a dated revocation
type AppAdminRole struct {
	AccountID pgtype.UUID
	// Administrative capability: moderator, admin or security; policy enforcement lives in the moderation application layer (P13-T02)
	Role string
	// Acting account that granted the role; immutable provenance of the assignment
	GrantedBy pgtype.UUID
	GrantedAt pgtype.Timestamptz
	// Instant the role was revoked, when it was; NULL while the assignment is active
	RevokedAt pgtype.Timestamptz
}

// Arena aggregation root: immutable published statement and fixed content language, mutable lifecycle status
type AppArena struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	// Stable public address assigned at publication; never an identity substitute
	Slug      pgtype.Text
	Statement string
	Context   pgtype.Text
	Category  string
	// Immutable content language of the Arena (pt-BR or en-US); independent from the interface locale
	Language string
	Status   string
	// Optimistic concurrency version, incremented on every accepted mutation
	Version     int32
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	ClosesAt    pgtype.Timestamptz
}

// Append-only Arena Pass consumptions; one row per published Arena, never updated or deleted at runtime
type AppArenaPassConsumption struct {
	ID         pgtype.UUID
	LotID      pgtype.UUID
	ArenaID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// Arena Pass lots: origin, granted quantity, optional immutable expiration and stable reference
type AppArenaPassLot struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Origin    string
	Quantity  int32
	// Consumable projection of the lot; over-consumption fails the CHECK constraint
	RemainingQuantity int32
	// Optional immutable expiration (NULL never expires); Member lots expire at their period end
	ExpiresAt pgtype.Timestamptz
	Reference string
	CreatedAt pgtype.Timestamptz
}

// Rebuildable public Arena count projection; normalized Arena, position and attribution tables remain authoritative
type AppArenaPublicStatProjection struct {
	ArenaID           pgtype.UUID
	ProjectionVersion int32
	// Latest source instant observed by the rebuild; it is not a wall-clock freshness claim
	SourceWatermark pgtype.Timestamptz
	Stats           []byte
	RebuiltAt       pgtype.Timestamptz
}

// Substitution/continuation notes linking one Arena to another (never to itself)
type AppArenaRelation struct {
	ID             pgtype.UUID
	ArenaID        pgtype.UUID
	RelatedArenaID pgtype.UUID
	Relation       string
	CreatedAt      pgtype.Timestamptz
}

// Public immutable argument or reply of one Arena: plaintext, canonical content hash, grapheme cost and withdrawal/moderation status
type AppArgument struct {
	ID       pgtype.UUID
	ArenaID  pgtype.UUID
	AuthorID pgtype.UUID
	ParentID pgtype.UUID
	// Declared relation to the Arena statement: support, oppose or context
	Relation string
	// Plaintext content as published; never edited after publication
	Content string
	// Versioned canonical hash of the content (format owned by the domain)
	ContentHash string
	// Grapheme cluster count: the 1 INK per cluster billing unit, at most 3000
	GraphemeCost int32
	// published, withdrawn (author) or removed (moderation); transitions are use-case rules
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	// Client attempt key, unique per author: a retry resolves the recorded argument instead of debiting INK again
	IdempotencyKey pgtype.Text
	// Instant of the author withdrawal; kept as the audit fact of the retraction, never a deletion
	WithdrawnAt pgtype.Timestamptz
}

// Structured sources supporting an argument: URL plus optional short description; a source never certifies truth
type AppArgumentSource struct {
	ID         pgtype.UUID
	ArgumentID pgtype.UUID
	// Absolute http(s) URL, bounded and free of whitespace
	Url         string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// Append-only administrative audit trail: one immutable row per administrative fact, readable by support and auditors, never rewritten
type AppAuditEvent struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
	ActorID    pgtype.UUID
	// Namespaced stable operation code (module.operation); greppable across wallet, moderation, billing and admin sources
	Action string
	// Closed target vocabulary; the identifier lives in target_id
	TargetType string
	TargetID   string
	// Stable reason or rule code; free prose never enters this column
	ReasonCode string
	// Minimal allowlisted JSONB object (identifiers, references, transitions); payloads, secrets and PII are unrepresentable
	Metadata []byte
	// Caller-chosen retry key, unique when set; NULL records unconditionally
	IdempotencyKey pgtype.Text
	// Optional opaque correlation grouping related events recorded together
	CorrelationID pgtype.Text
}

// Gateway charge verdicts per purchase intent: paid or failed facts the reconciliation compares, append-only
type AppBillingInkChargeEvent struct {
	ID          pgtype.UUID
	EventID     string
	IntentKey   string
	AccountID   pgtype.UUID
	AmountMinor int64
	Currency    string
	Status      string
	ReceivedAt  pgtype.Timestamptz
}

// Reversed INK liquidations: holder revocation plus treasury cover per provider dispute, append-only
type AppBillingInkChargeback struct {
	ID            pgtype.UUID
	SettlementID  pgtype.UUID
	EventID       string
	DisputedMinor int64
	// MilliINK taken back from the defrauding holder balance, never below zero
	InkRevoked int64
	// MilliINK the operator covered from commercial stock when the holder balance fell short
	TreasuryCovered int64
	ReceivedAt      pgtype.Timestamptz
}

// Accepted INK purchase intents: buyer, sealed quotation, server-derived amounts, terms hash and backing hold, append-only
type AppBillingInkIntent struct {
	ID pgtype.UUID
	// Caller operation token scoped by account: a retry replays instead of provisioning twice
	IntentKey string
	AccountID pgtype.UUID
	QuoteID   pgtype.UUID
	FiatMinor int64
	InkMilli  int64
	TermsHash string
	Status    string
	// Commercial-stock hold backing the intent, written by the same transaction
	HoldID    pgtype.UUID
	DecidedAt pgtype.Timestamptz
	// Book identity of this purchase: vault, hold and legs settle in the same book; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
}

// Paid INK purchase liquidations: one row per settled intent with its provider event, append-only
type AppBillingInkSettlement struct {
	ID       pgtype.UUID
	IntentID pgtype.UUID
	// Provider event identifier: redeliveries replay instead of settling again
	EventID     string
	AmountMinor int64
	Currency    string
	SettledAt   pgtype.Timestamptz
	// Book identity of this liquidation: the receipt never leaves its book; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
}

// Divergences found between the local state and the provider; recorded so they are reviewed instead of silently corrected
type AppBillingReconciliationFinding struct {
	ID    pgtype.UUID
	RunID pgtype.UUID
	// Account the divergence concerns; NULL when the object exists only on the provider side
	AccountID pgtype.UUID
	Kind      string
	// Private reference of the diverging object (local identifier or provider identifier); never part of a public projection, export or log
	Reference  string
	Details    pgtype.Text
	ObservedAt pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
	// Justification written when the finding is resolved; the rest of the record is immutable
	Resolution pgtype.Text
}

// Reconciliation windows already inspected, with the outcome the job reported; job-level execution bookkeeping belongs to the jobs module
type AppBillingReconciliationRun struct {
	ID       pgtype.UUID
	Livemode bool
	// Inclusive start of the inspected window (half-open with window_end)
	WindowStart    pgtype.Timestamptz
	WindowEnd      pgtype.Timestamptz
	Status         string
	ScannedObjects int32
	FindingsCount  int32
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

// Explicit refund and chargeback records: one row per provider refund/dispute object, with the compensating quantities and the human review flag
type AppBillingRefund struct {
	ID               pgtype.UUID
	AccountID        pgtype.UUID
	CheckoutIntentID pgtype.UUID
	// Private provider refund (re_...) or dispute (dp_...) identifier; the idempotency anchor of the compensation, never part of a public projection, export or log
	ProviderRefundID string
	// Whether the money was returned (refund) or contested (dispute/chargeback); disputes always wait for review
	Source string
	// Explicit outcome: applied when the unused benefit covered the reversal, needs_review when support/fraud must decide
	Status              string
	ChargedAmountMinor  int64
	RefundedAmountMinor int64
	// Purchased INK withdrawn by the compensating debit_refund entry; capped at the available balance so consumption never becomes a negative balance
	InkRevoked int64
	// Remaining purchased passes revoked by zeroing the lot projection; consumed passes are never rewritten, they become review
	PassesRevoked int32
	// True when part of the benefit was already consumed, the refund was partial over passes, the source was a dispute, or nothing reversible remained
	NeedsReview bool
	// Machine-readable reason the row waits for review (for example already_consumed, partial_pass_refund, chargeback)
	ReviewReason pgtype.Text
	CreatedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
	// Justification written when a human resolves the review; the rest of the record is immutable
	Resolution pgtype.Text
}

// Editorial Arena categories; seeded by migrations, display names resolve through the versioned i18n catalogs
type AppCategory struct {
	Slug         string
	DisplayOrder int32
	CreatedAt    pgtype.Timestamptz
}

// Server-authoritative checkout intents: the local record of the commercial decision and its provider correlation; only a verified webhook settles one
type AppCheckoutIntent struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	// Commercial region resolved by the server (never inferred from IP) with the currency it charges
	Market string
	// Versioned catalog product (lower snake case), the same vocabulary as the billing domain
	ProductID string
	// Catalog version that was in force when the price was resolved, so an old purchase stays explainable after a price change
	CatalogVersion int32
	Currency       string
	// Exact price in minor units of the currency, as resolved from the catalog; never provided by the browser
	AmountMinor int64
	Livemode    bool
	Status      string
	// Private Stripe checkout session identifier (cs_...); its prefix is pinned to livemode
	StripeCheckoutSessionID pgtype.Text
	// Private Stripe payment intent identifier (pi_...), kept for refund and dispute correlation
	StripePaymentIntentID pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	// Instant the provider confirmed the payment; success pages never set it
	PaidAt pgtype.Timestamptz
	// Instant the intent closed without payment (expired or failed)
	ClosedAt pgtype.Timestamptz
}

// Funded formal trade contracts: idempotency key, service object, parties, exact amount, sealed terms and locking transfer, append-only
type AppCommerceContract struct {
	ID pgtype.UUID
	// Caller operation token scoped by buyer: a retry replays instead of locking twice
	ContractKey string
	Kind        string
	BuyerID     pgtype.UUID
	ProviderID  pgtype.UUID
	Object      string
	AmountMilli int64
	TermsHash   string
	// Journal transfer that locked the buyer amount in exclusive escrow
	EscrowTransferID pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
	PostedAt         pgtype.Timestamptz
	// Book identity of this escrow: the locked legs settle in the same book; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
	// Terminal clause reference of section 5.1: versioned policy accepted by both parties before funding; empty on legacy contracts without the clause
	TerminalPolicyRef string
	// Digest of the terminal clause (64 lowercase hex) bound at funding; empty on legacy contracts without the clause
	TerminalPolicyHash string
	// Buyer accept evidence recorded before funding; empty on legacy contracts without the clause
	BuyerAcceptRef string
	// Provider accept evidence recorded before funding; empty on legacy contracts without the clause
	ProviderAcceptRef string
}

// Flagged gifts under review for disguised trade: caller token, closed reason, minimized evidence digest and reporter, append-only, never moves value
type AppCommerceDisguiseReview struct {
	ID         pgtype.UUID
	TransferID pgtype.UUID
	// Caller operation token scoped by transfer: a retry replays instead of reviewing twice
	ReviewKey string
	Reason    string
	// Minimized proof digest (64 lowercase hex): no PII content ever stored
	EvidenceHash string
	Reporter     string
	PostedAt     pgtype.Timestamptz
}

// Review lifecycle steps: party contest, false-positive dismissal and confirmed act with basis, trail, explicit charge and appeal window, append-only, never moves value
type AppCommerceDisguiseStep struct {
	ID        pgtype.UUID
	ReviewID  pgtype.UUID
	Action    string
	DecidedBy string
	// Contractual basis of a confirmed act: required only for confirm, never for contest or dismissal
	Basis     pgtype.Text
	TrailHash pgtype.Text
	// Explicit floor(10%) charge owed on confirmation: recorded debt with appeal, never an automatic debit
	ChargeMilli pgtype.Int8
	AppealUntil pgtype.Timestamptz
	PostedAt    pgtype.Timestamptz
}

// Explicit shortfall debts: at most one per service refund, naming the provider debtor, the buyer creditor and the uncovered share, append-only
type AppCommerceRefundObligation struct {
	ID          pgtype.UUID
	RefundID    pgtype.UUID
	DebtorID    pgtype.UUID
	CreditorID  pgtype.UUID
	AmountMilli int64
	PostedAt    pgtype.Timestamptz
}

// Sanctioned accounts blocked from paying and receiving: rows are managed by governance, read by settlement
type AppCommerceSanction struct {
	// Blocked account: payer and payee checks run in the settling transaction
	AccountID pgtype.UUID
	Reason    string
	DecidedAt pgtype.Timestamptz
}

// Proportional service refunds linked to their liquidated payment: idempotency key, total returned, tithe reversal, provider share, explicit shortfall and moving transfer, append-only
type AppCommerceServiceRefund struct {
	ID         pgtype.UUID
	ContractID pgtype.UUID
	// Caller operation token scoped by contract: a retry replays instead of compensating twice
	RefundKey          string
	AmountMilli        int64
	TitheReversalMilli int64
	ProviderShareMilli int64
	// Shortfall the provider could not cover: explicit debt to the buyer, never a hidden negative balance
	ObligationMilli int64
	// Journal transfer moving provider share and tithe reversal to the buyer; NULL only when dust plus a broke provider moves nothing and the full share becomes obligation
	TransferID pgtype.UUID
	PostedAt   pgtype.Timestamptz
}

// Escrow lifecycle steps: acceptance, provider payment, buyer refund, lapse marking and competent resolutions, append-only
type AppCommerceSettlement struct {
	ID         pgtype.UUID
	ContractID pgtype.UUID
	// Lifecycle step: accept and expire move no legs; release, refund and resolutions move under new transfers
	Action     string
	TransferID pgtype.UUID
	DecidedBy  pgtype.Text
	PostedAt   pgtype.Timestamptz
}

// Settled voluntary transfers: idempotency key, immutable kind, payer, payee, exact amount, consent reference and journal transfer, append-only
type AppCommerceTransfer struct {
	ID pgtype.UUID
	// Caller operation token scoped by payer: a retry replays instead of paying twice
	IntentionKey string
	// Business kind sealed at acceptance: gifts, formal trades, refunds and treasury movements never interchange
	Kind        string
	PayerID     pgtype.UUID
	PayeeID     pgtype.UUID
	AmountMilli int64
	ConsentRef  string
	PayloadHash string
	// Journal transfer moving the exact amount: row and legs share one intention
	TransferID pgtype.UUID
	PostedAt   pgtype.Timestamptz
	// Book identity of this transfer: the legs settle in the same book; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
}

// Explicit communication opt-ins per account; marketing defaults to false and is never opted in implicitly
type AppCommunicationPreference struct {
	AccountID pgtype.UUID
	// Explicit marketing consent; false by default and only the account owner may change it
	MarketingOptIn bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Append-only audit trail of every explicit communication preference change
type AppCommunicationPreferenceHistory struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	MarketingOptIn bool
	ChangedAt      pgtype.Timestamptz
}

// Personal data export jobs: owner-scoped, token-protected, expiring and download-limited; the document never contains restricted antifraud or provider secret data
type AppDataExport struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Status    string
	// SHA-256 of the opaque download token; the raw capability is returned exactly once to the owner
	DownloadTokenHash []byte
	RequestedAt       pgtype.Timestamptz
	GeneratedAt       pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	// Versioned machine-readable export document (JSON text), immutable once written
	Document pgtype.Text
	// SHA-256 of the exact document bytes served to the owner
	DocumentSha256 pgtype.Text
	DownloadCount  int32
	// Download budget frozen per export: policy changes never retrofit existing records
	MaxDownloads     int32
	LastDownloadedAt pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Private projection of one account position in one Arena: immutable initial choice plus current choice and optimistic version
type AppDebatePosition struct {
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
	// Immutable first confirmed position; the history chain starts here at version 1
	InitialPosition string
	// Derived projection of the chain tip; must equal the last accepted change target
	CurrentPosition string
	// Optimistic concurrency version: 1 at confirmation, +1 per accepted change
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Staged private case records: one sealed CaseRecord envelope per negotiation key (P56-T03)
type AppDisputeCase struct {
	// Negotiation key the parties address, at most 128 characters
	Key string
	// Sealed CaseRecord envelope: proposal, entry, hearing and decision as filed
	Record    []byte
	UpdatedAt pgtype.Timestamptz
}

// Versioned charter verdicts per account: acceptance unlocks new activities, refusal preserves history, export, recourse and settlement
type AppEconomyCharterConsent struct {
	AccountID pgtype.UUID
	// Charter version as vN: acceptances never carry across versions silently
	CharterVersion string
	Decision       string
	DecidedAt      pgtype.Timestamptz
}

// Genesis custody accounts: exactly one home per unit of INK, never renamed or removed
type AppEconomyCustody struct {
	ID pgtype.UUID
	// Custody class: treasury, user, escrow, contract or title; closed vocabulary
	Kind string
	// Stable custody name within its kind; unique per kind
	Label     string
	CreatedAt pgtype.Timestamptz
	// Holder account of this custody, set once at creation; NULL marks a system custody no private statement may read
	OwnerAccountID pgtype.UUID
	// Book identity of this custody: the same label in another book is another custody; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
}

// Double-entry legs of Genesis transfers: debit/credit pairs sharing one transfer_id, append-only
type AppEconomyEntry struct {
	ID pgtype.UUID
	// Business intention carried by every leg of the transfer; replayed intentions reuse it instead of duplicating legs
	TransferID pgtype.UUID
	CustodyID  pgtype.UUID
	Direction  string
	// Leg amount in milliINK subunits: 1..S, never zero, negative or beyond supply
	AmountMilli int64
	CreatedAt   pgtype.Timestamptz
	// Book of this leg: the composite key refuses legs mixing a custody of another book
	SeasonKey string
}

// Single Genesis attestation: one event key, the Treasury custody and exactly S milliINK; every second event is refused
type AppEconomyGenesi struct {
	// Idempotency key of the creation event: replays resolve to this row instead of minting again
	GenesisKey        string
	TreasuryCustodyID pgtype.UUID
	AmountMilli       int64
	// Always true and unique: the constraint that makes a second Genesis impossible
	Singleton bool
	CreatedAt pgtype.Timestamptz
	// Book identity of this Genesis: one Genesis per season, never twice in one book
	SeasonKey string
}

// Generic value holds: owner funds locked in a dedicated hold custody until an explicit release or capture; expiry alone moves nothing
type AppEconomyHold struct {
	ID pgtype.UUID
	// Custody the funds were reserved from; its spendable balance excludes active and expired-unsettled holds
	OwnerCustodyID pgtype.UUID
	// Dedicated escrow-kind custody holding the locked amount; one hold per custody
	HoldCustodyID pgtype.UUID
	AmountMilli   int64
	Purpose       string
	ExpiresAt     pgtype.Timestamptz
	// Closed machine: active settles to released, captured or expired; expired still settles to released or captured
	Status    string
	CreatedAt pgtype.Timestamptz
	ClosedAt  pgtype.Timestamptz
	// Book of this hold: owner and hold custodies must live in the same book
	SeasonKey string
}

// Audit trail of conservation breaks and their compensated resolutions; rows are never edited or erased
type AppEconomyIncident struct {
	ID     pgtype.UUID
	Reason string
	Detail string
	// Incident this resolution closes; NULL marks the break itself
	Resolves  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// Exactly-once registry of monetary intentions: one triple, one payload hash, one settled transfer with its persisted response
type AppEconomyIntention struct {
	IntentionKey string
	Actor        string
	Operation    string
	// SHA-256 hex of the canonical transfer payload: a different payload under the same triple is a conflict
	PayloadHash string
	// Transfer settled by this intention; unique so one transfer answers exactly one intention
	TransferID  pgtype.UUID
	AmountMilli int64
	CreatedAt   pgtype.Timestamptz
	// Book of this intention: replays resolve per book, never redirecting another book outcome
	SeasonKey string
}

// Single read-only flag of the economy: mutations recheck it, reads never do
type AppEconomyMode struct {
	Singleton bool
	Frozen    bool
	// Break that froze the book, or the last one after a compensated resolution
	IncidentID pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
}

// Explicit economic opt-in intents: quantity, conversion rate and validity recorded verbatim for exact matching at conversion; one intent per account and charter version
type AppEconomyOptin struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	CharterVersion string
	QuantityMilli  int64
	// Conversion rate numerator in milliINK per legacy INK unit, with rate_den: exact rational, never rounded
	RateNum int64
	// Conversion rate denominator in legacy INK units
	RateDen    int64
	ValidUntil pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Exclusive sub-partitions of one custody: reserve, stock, cash, obligations and encumbrances never double-count
type AppEconomyPartition struct {
	ID pgtype.UUID
	// Owning custody; restricted from deletion while partitions exist
	CustodyID pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

// Single-use cryptographic token hashes for email verification
type AppEmailVerificationToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Durable job queue: one row per unit of work, leased with SKIP LOCKED and recoverable after a crashed holder
type AppJob struct {
	ID pgtype.UUID
	// Closed workload vocabulary; handlers per type arrive with the worker
	Type string
	// Schema version of the payload; a bump is an explicit, reviewable change
	Version int32
	// Bounded JSON object with identifiers, references and arguments (the job payload); rendered output, credentials and free prose are unrepresentable
	Parameters []byte
	// Caller-chosen retry key, unique when set; NULL enqueues unconditionally
	IdempotencyKey pgtype.Text
	// Lifecycle: queued, leased, succeeded or dead
	State string
	// Earliest instant the job may run (also the retry instant after a failure)
	AvailableAt pgtype.Timestamptz
	// Attempts already consumed; bounded by max_attempts
	Attempts    int32
	MaxAttempts int32
	// Worker that holds the lease; NULL for every non-leased row
	LeaseOwner pgtype.Text
	// Instant the lease expires and the job becomes claimable again
	LeasedUntil pgtype.Timestamptz
	// Stable redacted code (JOB_*) of the last failure; never a provider message
	LastErrorCode pgtype.Text
	// Bounded, already-sanitized failure detail; never a stack trace or payload echo
	LastErrorDetail pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Settled INK publication charges: idempotency key, publisher, sealed price terms, canonical hashes, journal transfer and database posted instant, append-only
type AppMeteringPublication struct {
	ID pgtype.UUID
	// Caller operation token scoped by account: a retry replays instead of charging twice
	IntentionKey string
	AccountLabel string
	Service      string
	PriceVersion int32
	Units        int32
	AmountMilli  int64
	ContentHash  string
	QuoteHash    string
	PayloadHash  string
	// Journal transfer moving the exact quoted cost: statement and content share one intention
	TransferID pgtype.UUID
	// Database clock at write, visible only after commit: never a request or browser instant
	PostedAt pgtype.Timestamptz
	// Book identity of this publication: the legs settle in the same book; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
}

// Publication compensations: refund key, owner, compensated publication, reversed amount, compensating transfer and database posted instant, append-only
type AppMeteringRefund struct {
	ID           pgtype.UUID
	RefundKey    string
	AccountLabel string
	// Compensated publication: the cause the correction links to without editing
	OriginalID  pgtype.UUID
	AmountMilli int64
	TransferID  pgtype.UUID
	Reason      string
	// Database clock at write, always current: corrections never backdate into closed periods
	PostedAt pgtype.Timestamptz
}

// One-time recovery codes of an MFA enrollment, stored hashed and spent exactly once (P16-T05)
type AppMfaBackupCode struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	CodeHash  string
	// Set by the single UPDATE that spends the code; NULL means the code is still usable
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Immutable sanction facts of a case: actor, applied rule, restricted justification and optional expiry; reversals are new rows, never edits
type AppModerationAction struct {
	ID         pgtype.UUID
	CaseID     pgtype.UUID
	ActionType string
	ActorID    pgtype.UUID
	// Stable rule reference applied by the moderator (for example MOD-3:spam); policy neutrality is tested in P13-T08
	RuleApplied string
	// Restricted internal justification up to 2000 chars; never part of a public projection
	Justification string
	// Expiry of time-boxed measures (suspension, interaction_limit); required exactly for those, forbidden for the rest
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Restricted appeal per action: exactly one appeal contests one action; review outcome is appended once by a reviewer
type AppModerationAppeal struct {
	ID pgtype.UUID
	// Contested action; UNIQUE enforces one appeal per action when applicable
	ActionID    pgtype.UUID
	AppellantID pgtype.UUID
	Status      string
	// Appellant context up to 2000 chars; restricted evidence, never part of a public projection
	Context    string
	ReviewerID pgtype.UUID
	// Reviewer justification written once when the appeal is decided; the rest of the record is immutable
	DecisionReason pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

// Moderation case per target with an explicit triage lifecycle; reporter evidence stays in reports, decisions stay in actions
type AppModerationCase struct {
	ID               pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	// Triage lifecycle: open -> under_review -> decided -> closed; enforced by trigger
	Status string
	// Triage priority: low, normal, high or urgent; mutable without moving the lifecycle
	Priority  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ClosedAt  pgtype.Timestamptz
	// Reviewing moderator holding the case; NULL unless the case is under review
	ClaimedBy pgtype.UUID
	// Instant the claim was taken; moves with claimed_by
	ClaimedAt pgtype.Timestamptz
	// Bounded claim lease: a live lease serializes concurrent claims, an expired lease may be reclaimed by another moderator
	LeaseExpiresAt pgtype.Timestamptz
}

// Restricted report evidence: reporter, structured reason and optional context; never part of a public projection
type AppModerationReport struct {
	ID               pgtype.UUID
	ReporterID       pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	// Closed reason vocabulary from MODERATION §3; free text lives only in context
	Reason string
	// Optional reporter context up to 2000 chars; restricted evidence, never logged or exported
	Context   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

// Hashed password credentials isolated from public account and profile data
type AppPasswordCredential struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Single-use cryptographic token hashes for password recovery
type AppPasswordResetToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Private influence attributions: one position change credits one argument; the attributor identity is never part of a public projection
type AppPersuasionAttribution struct {
	ID               pgtype.UUID
	PositionChangeID pgtype.UUID
	// Account that made the position change; coherent with the change through the composite foreign key and private by default
	AttributorID pgtype.UUID
	ArgumentID   pgtype.UUID
	// valid or invalid (moderation/fraud); invalidation never deletes the historical row
	Status        string
	CreatedAt     pgtype.Timestamptz
	InvalidatedAt pgtype.Timestamptz
	// Mandatory justification of the latest moderation decision; never cleared, so the decision stays recorded without deleting the row
	ModerationReason pgtype.Text
	// Moderator account that took the latest decision (invalidate or restore)
	ModeratedBy pgtype.UUID
	// Instant of the latest moderation decision; coincides with invalidated_at while the attribution is invalid
	ModeratedAt pgtype.Timestamptz
}

// Append-only chain of accepted position changes; from_position and to_position always differ
type AppPositionChange struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AccountID    pgtype.UUID
	FromPosition string
	ToPosition   string
	// Resulting projection version after the change; the chain starts at 2
	Version int32
	// Instant of the accepted change; ordering authority is version
	ChangedAt pgtype.Timestamptz
}

// Accepted BTC/BRL quotation snapshots: integer price, observed/accepted/expiry instants and content hash, append-only
type AppPricingQuote struct {
	ID pgtype.UUID
	// Guarded median in integer minor units (centavos per BTC): never float
	PriceMinor int64
	ObservedAt pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	// Canonical hash binding price, ordered sources and instants: tampering is detectable by recomputation
	QuoteHash string
	// Book identity of this quotation: expiry is capped by the book end at acceptance; pre-season rows bind the explicitly inactive compat-legacy namespace
	SeasonKey string
}

// One sighting per source and quote: the frozen source set the acceptance judged
type AppPricingQuoteSource struct {
	QuoteID     pgtype.UUID
	Source      string
	PriceMinor  int64
	ObservedAt  pgtype.Timestamptz
	PayloadHash string
}

// Account profiles: public username and interface locale, without email or payment identifiers
type AppProfile struct {
	AccountID pgtype.UUID
	Username  string
	// Canonical ASCII-lowercase username; sole uniqueness/authority key for lookups
	UsernameNormalized string
	InterfaceLocale    string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	// Optional IANA timezone preference of the account; NULL means not informed (UTC fallback)
	Timezone pgtype.Text
}

// Legal and contractual holds: while a hold is active the retention job purges and anonymizes nothing for the held class or account; holds are never deleted
type AppRetentionHold struct {
	ID pgtype.UUID
	// Governed retention class, the same closed vocabulary the executable policy declares
	DataClass string
	// Held account; NULL holds the whole class
	AccountID pgtype.UUID
	// Stable reason code of the hold (never free prose)
	ReasonCode string
	// Administrative account that placed the hold; retained as provenance
	PlacedBy   pgtype.UUID
	PlacedAt   pgtype.Timestamptz
	ReleasedAt pgtype.Timestamptz
	// Stable reason code written once when the hold is released
	ReleaseReasonCode pgtype.Text
}

// Append-only retention ledger: one row per governed class and execution with counts only, so enforcement is auditable without storing any content
type AppRetentionRun struct {
	ID pgtype.UUID
	// Governed retention class the run enforced
	DataClass string
	// Instant the run enforced the schedule, from the injected clock
	ExecutedAt pgtype.Timestamptz
	// Terminal boundary the run applied (now minus the class window); NULL for classes retained without a purge horizon
	CutoffAt pgtype.Timestamptz
	// Records removed by the run
	PurgedCount int32
	// Records whose restricted references were stripped by the run
	AnonymizedCount int32
	// Records kept under a retention obligation by the run
	RetainedCount int32
	// Records the run preserved because an active legal hold covered them
	HeldCount int32
}

// goose forward-only migration history for the app schema (schema_metadata version table required by the master plan)
type AppSchemaMetadatum struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

// Immutable season plan registry: key, ordinal, exact ninety-day UTC window, charter, policy, initial holder data and sealed manifesto; never activated here
type AppSeason struct {
	// Immutable book identity (INK@season_id): pre-season technical data uses the explicitly inactive compat-legacy namespace
	SeasonKey string
	// Calendar order from 1; 0 is reserved for the explicitly inactive pre-season compatibility namespace
	Ordinal  int32
	StartsAt pgtype.Timestamptz
	// Exclusive end, always starts_at plus 7776000 seconds: civil months and DST never enter the calendar
	EndsAt         pgtype.Timestamptz
	CharterVersion string
	PolicyRef      string
	InitialMonarch string
	Regent         string
	// Sealed manifesto digest (64 lowercase hex): altered manifests never open a season
	ManifestHash string
	CreatedAt    pgtype.Timestamptz
}

// Sealed book receipts: cutoff, seal instant, Genesis S, leg and intention counts and manifesto digest; one row per archived book, never rewritten
type AppSeasonArchive struct {
	// Archived book: one receipt per sealed book, so two openers archive exactly once
	SeasonKey string
	// Barrier instant on the database clock carried from the close run
	CutoffAt pgtype.Timestamptz
	// Seal instant from the lifecycle sealed stage
	SealedAt pgtype.Timestamptz
	// Book Genesis S at the seal: opening requires it byte-equal, so nothing mints and nothing crosses
	SnapshotMilli      int64
	SnapshotLegs       int64
	SnapshotIntentions int64
	// Sealed manifesto digest (64 lowercase hex): adulterated manifests never open a successor
	ManifestHash string
	CreatedAt    pgtype.Timestamptz
}

// Seasonal closing barrier runs: one fenced run per book with generation, lease, checkpoint cursors and the cutoff conservation snapshot; money never moves here
type AppSeasonCloseRun struct {
	// Book under closing: one run per book, so two closers open exactly one barrier
	SeasonKey string
	// Monotonic fence: every drain write carries it, stale workers move nothing, takeover bumps it by one past an expired lease
	Generation int64
	// Opaque worker holding the book until leased_until on the database clock
	LeaseOwner  string
	LeasedUntil pgtype.Timestamptz
	State       string
	// Barrier instant on the database clock: admissions checked after it refuse, admitted in-flight work still completes once
	CutoffAt pgtype.Timestamptz
	// Checkpoint cursor over economy holds in key order: crash before commit replays, crash after resumes past it
	LastHoldKey string
	// Checkpoint cursor over commerce escrows in key order, with the same replay promise
	LastEscrowKey string
	Drained       int64
	Blocked       int64
	// Book Genesis S at the barrier: Seal requires it byte-equal, so nothing mints and nothing crosses
	SnapshotMilli      int64
	SnapshotLegs       int64
	SnapshotIntentions int64
	ErrorCode          string
	ErrorDetail        string
	UpdatedAt          pgtype.Timestamptz
}

// Append-only season stage events: state derives from the latest event, never by rewriting; at most one active season exists
type AppSeasonLifecycle struct {
	ID        pgtype.UUID
	SeasonKey string
	// Previous stage, NULL on the opening prepared event
	FromState pgtype.Text
	// New stage: a second active season dies on the partial unique index
	ToState    string
	DecidedAt  pgtype.Timestamptz
	RecordedAt pgtype.Timestamptz
}

// Sovereign reigns: records active and historical monarchs/regents per season with strict single-active constraint
type AppSeasonalReign struct {
	ID pgtype.UUID
	// Season book identity
	SeasonID string
	// Investiture sequence number within the season (starts at 1)
	ReignVersion int32
	// Account identifier of the reigning monarch or regent
	HolderSubject      string
	IsRegent           bool
	Reason             string
	InstitutionalC     int64
	WinningWealth      int64
	AttainedRevision   int64
	TransitionRevision int64
	Predecessor        string
	// True if this reign is the currently invested authority in this season
	IsActive  bool
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Evaluator checkpoint and worker lease tracking for linearizable succession processing
type AppSeasonalSuccessionEvaluator struct {
	SeasonID              string
	LastEvaluatedRevision int64
	ActiveWorkerID        string
	LeaseExpiresAt        pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// Linearizable notification outbox for sovereign successions, written atomically with reign transitions
type AppSeasonalSuccessionEvent struct {
	ID                 pgtype.UUID
	SeasonID           string
	ReignVersion       int32
	EventKind          string
	SuccessorSubject   string
	PredecessorSubject string
	InstitutionalC     int64
	WinningWealth      int64
	TransitionRevision int64
	Payload            []byte
	CreatedAt          pgtype.Timestamptz
}

// Checkpoint tracking last processed revision and integrity hash per season book
type AppSeasonalWealthCheckpoint struct {
	SeasonID       string
	LastRevision   int64
	CheckpointHash string
	Frozen         bool
	UpdatedAt      pgtype.Timestamptz
}

// Linearizable outbox of committed wealth changes, updated within financial transactions
type AppSeasonalWealthEvent struct {
	ID               pgtype.UUID
	SeasonID         string
	Revision         int64
	SubjectID        string
	BeneficiaryKind  string
	EventKind        string
	DeltaAssets      int64
	DeltaLiabilities int64
	SourceRef        string
	CreatedAt        pgtype.Timestamptz
}

// Confirmed registered seasonal debts and obligations contributing to L(b)
type AppSeasonalWealthObligation struct {
	ID              pgtype.UUID
	SeasonID        string
	DebtorSubject   string
	ObligationKind  string
	AmountMilli     int64
	AlreadyDeducted bool
	SourceRef       string
	CreatedAt       pgtype.Timestamptz
}

// Rebuildable seasonal wealth projections: indexes W(b) without replacing the authoritative journal
type AppSeasonalWealthProjection struct {
	// Season book identity
	SeasonID string
	// Beneficiary subject account identifier
	SubjectID        string
	BeneficiaryKind  string
	AssetsMilli      int64
	LiabilitiesMilli int64
	// Derived beneficial wealth W(b) = max(0, assets - liabilities)
	Wealth int64
	// Revision when current wealth level was attained; breaks ties by seniority
	AttainedRevision int64
	Frozen           bool
	Eligible         bool
	SourceWatermark  pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Opaque server-side session store with revocation and inactivity tracking
type AppSession struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
	// Instant the session presented a second factor; NULL means the session is not MFA-elevated (P16-T05)
	MfaVerifiedAt pgtype.Timestamptz
}

// Mapping between a local account and its Stripe customer; the provider identifier is private and never leaves the billing module
type AppStripeCustomer struct {
	AccountID pgtype.UUID
	// Private Stripe customer identifier (cus_...); shape checked, never part of a public projection, export or log
	StripeCustomerID string
	// Stripe mode the customer belongs to; pinned so test and live objects can never be mixed for one account
	Livemode  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Verified Stripe webhook events: the unique provider event id makes redelivery harmless, and the raw payload is never persisted
type AppStripeEvent struct {
	ID pgtype.UUID
	// Unique provider event identifier (evt_...); the idempotency anchor of the webhook (REQ-BIL-03, THR-STRIPE-03)
	StripeEventID string
	EventType     string
	Livemode      bool
	// Provider creation instant of the event, kept so out-of-order deliveries can be reasoned about
	StripeCreatedAt pgtype.Timestamptz
	// SHA-256 of the exact raw body: evidence of integrity and duplication without storing the payload (which may carry personal data)
	PayloadSha256 string
	// Size in bytes of the exact raw body that was verified
	PayloadBytes int32
	Status       string
	// Number of times the event was claimed for processing; retries reuse this row instead of inserting a new one
	Attempts int32
	// Bounded reason of the latest failure; exists only while status is failed and is cleared on retry
	LastError   pgtype.Text
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

// Mirror of the provider subscription state; the entitlement franchises of a period are granted from this state and never from a browser visit
type AppSubscription struct {
	ID                   pgtype.UUID
	AccountID            pgtype.UUID
	StripeSubscriptionID string
	// Provider status vocabulary; canceled and incomplete_expired are terminal and can never revive
	Status         string
	Livemode       bool
	Market         string
	ProductID      string
	CatalogVersion int32
	// Private Stripe price in use by the subscription; compared against the versioned catalog by reconciliation
	StripePriceID string
	// Start of the billed period, the anchor of the per-period Member franchise
	CurrentPeriodStart pgtype.Timestamptz
	// End of the billed period; a period-bound pass expires here and the franchise does not accumulate
	CurrentPeriodEnd pgtype.Timestamptz
	// Provider cancellation scheduled for the end of the period; benefits last until then
	CancelAtPeriodEnd bool
	// Instant the provider registered the cancellation, when it reports one
	CanceledAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// Rebuildable period metrics projection; normalized source tables remain authoritative
type AppTransparencyStatProjection struct {
	PeriodStart        pgtype.Timestamptz
	PeriodEnd          pgtype.Timestamptz
	MethodologyVersion int32
	// Latest source instant observed by the period rebuild
	SourceWatermark pgtype.Timestamptz
	Stats           []byte
	RebuiltAt       pgtype.Timestamptz
}

// Governed Treasury disbursement acts: allowlisted purpose, origin vault, beneficiary, two distinct approvers and settling transfer, append-only
type AppTreasuryDisbursement struct {
	ID pgtype.UUID
	// Idempotency anchor of the act: a duplicated approval replays instead of paying twice
	DisbursementKey      string
	OriginVault          string
	BeneficiaryAccountID pgtype.UUID
	Purpose              string
	AmountMilli          int64
	ApproverOne          pgtype.UUID
	ApproverTwo          pgtype.UUID
	// Journal transfer that moved the amount: every row carries its legs
	TransferID pgtype.UUID
	DecidedAt  pgtype.Timestamptz
}

// Audit trail of every username set or changed by an account (P05-T02 requires auditable history)
type AppUsernameHistory struct {
	ID                 pgtype.UUID
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
	ChangedAt          pgtype.Timestamptz
}

// Cached INK balance projection per account and bucket; the append-only transaction ledger is the source of truth
type AppWalletAccount struct {
	AccountID pgtype.UUID
	// FREE_INK balance (plan franchise, consumed before purchased INK); never negative
	BalanceFree int64
	// PURCHASED_INK balance (bought INK, consumed after the franchise); never negative
	BalancePurchased int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	// Monthly FREE_INK cycle anchor (activation instant); immutable and evaluated in UTC
	FreeCycleAnchorAt pgtype.Timestamptz
}

// Append-only idempotency registry of logical INK operations (credit, debit, expiry)
type AppWalletOperation struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	OperationType string
	// Globally unique retry key: the same key is accepted exactly once
	IdempotencyKey string
	// Stable identifier of the cause (argument, Stripe event, moderation case, billing period)
	Reference string
	CreatedAt pgtype.Timestamptz
	// Mandatory justification of administrative adjustments; optional for regular operations
	Reason pgtype.Text
	// Acting administrator account for administrative adjustments; never modified after insert
	ActorAccountID pgtype.UUID
}

// Append-only INK ledger: signed bucket deltas (positive credit, negative debit); never updated or deleted at runtime
type AppWalletTransaction struct {
	ID          pgtype.UUID
	OperationID pgtype.UUID
	Bucket      string
	// Signed INK delta in bigint: positive credits the bucket, negative debits it; zero is forbidden
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
