// Package decoy is the negative half of the provenance probe, and the reason this
// gate reads the marker where the toolchain reads it instead of scanning bytes:
// the generators of this repository carry the marker inside a string, so a text
// search would exclude the very files that write generated code — while looking
// exactly like a rule that had done the right thing.
package decoy

import "context"

// generatedMarker is the header this generator writes into its output.
const generatedMarker = "// Code generated by decoy. DO NOT EDIT.\n"

// Dropped is judged, and it is not generated code: the marker above is data this
// file holds, not a comment about this file.
func Dropped(ctx context.Context) error { return nil }

type client struct{}

func (c *client) Do(ctx context.Context) (*response, error) { return &response{}, nil }

type response struct{}
