// Deterministic emission of the TypeScript transport contracts (P18-T02).
//
// The generator is deliberately limited to the subset of OpenAPI 3.1 that
// api/openapi.json actually uses, so the browser keeps TypeScript as its only
// build dependency:
//
//	supported  $ref, type (including ["T","null"]), enum, oneOf, format,
//	           properties, required, items
//	ignored    description, title, examples, default, deprecated and the
//	           numeric/string bound keywords: they document or constrain the
//	           value but never change the emitted TypeScript type
//	rejected   everything else (allOf, anyOf, not, additionalProperties,
//	           patternProperties, const, discriminator, nested object
//	           schemas, tuple items, unknown formats, dangling $ref), each
//	           failure naming the keyword and the JSON path that carries it
//
// Same contract -> byte-identical file: schemas and property names are
// sorted, so Go map iteration order can never leak into the artifact.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// generatedHeader marks the artifact as generated and states the readonly
// convention the frontend relies on (docs/FRONTEND.md section 6).
const generatedHeader = `// Code generated by tools/contractgen from api/openapi.json. DO NOT EDIT.
// Source of truth: api/openapi.json (the versioned HTTP contract).
// Readonly by convention: every emitted member is readonly.
`

// schemaRefPrefix is the only $ref form the contract uses.
const schemaRefPrefix = "#/components/schemas/"

// identifierPattern matches the property and schema names TypeScript can
// address without quoting.
var identifierPattern = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// supportedKeywords change the emitted TypeScript type.
var supportedKeywords = map[string]bool{
	"$ref":       true,
	"type":       true,
	"format":     true,
	"enum":       true,
	"properties": true,
	"required":   true,
	"items":      true,
	"oneOf":      true,
}

// ignoredKeywords document or bound the value without changing its type.
// The backend stays the authority that enforces them.
var ignoredKeywords = map[string]bool{
	"description":      true,
	"title":            true,
	"example":          true,
	"examples":         true,
	"default":          true,
	"deprecated":       true,
	"readOnly":         true,
	"writeOnly":        true,
	"pattern":          true,
	"minLength":        true,
	"maxLength":        true,
	"minimum":          true,
	"maximum":          true,
	"exclusiveMinimum": true,
	"exclusiveMaximum": true,
	"multipleOf":       true,
	"minItems":         true,
	"maxItems":         true,
	"uniqueItems":      true,
	"minProperties":    true,
	"maxProperties":    true,
}

// textFormats are string formats the frontend transports as `string`.
var textFormats = map[string]bool{
	"date-time":     true,
	"email":         true,
	"uri":           true,
	"uri-reference": true,
	"uuid":          true,
	"hostname":      true,
	"ipv4":          true,
	"ipv6":          true,
	"password":      true,
	"byte":          true,
	"duration":      true,
}

// numberFormats are numeric formats the frontend transports as `number`.
var numberFormats = map[string]bool{
	"double": true,
	"float":  true,
	"int32":  true,
	"int64":  true,
}

// rawSchema is one JSON Schema fragment exactly as it appears in the
// document. Keywords are inspected by name so an unsupported one can be
// reported together with the path that carries it.
type rawSchema = map[string]json.RawMessage

// document is the part of the contract the generator consumes.
type document struct {
	Paths      map[string]any `json:"paths"`
	Components struct {
		Schemas map[string]json.RawMessage `json:"schemas"`
	} `json:"components"`
}

// typeList decodes `type`, which OpenAPI 3.1 allows as either a single
// string or an array of strings (used here for nullable scalars).
type typeList []string

// UnmarshalJSON accepts both spellings of the `type` keyword.
func (types *typeList) UnmarshalJSON(data []byte) error {
	var single string
	if err := json.Unmarshal(data, &single); err == nil {
		*types = []string{single}
		return nil
	}
	var many []string
	if err := json.Unmarshal(data, &many); err != nil {
		return errors.New("type must be a string or an array of strings")
	}
	*types = many
	return nil
}

// headerFor names the true source contract in the emitted header. The
// default contract keeps the historical header byte-identical; staged
// fragments name their own fragment and state that they stay out of the
// published contract until activation, so a staged artifact never claims
// to come from api/openapi.json.
func headerFor(contractPath string) string {
	if filepath.Base(contractPath) == "openapi.json" {
		return generatedHeader
	}
	// Canonicalize the source label so the artifact is byte-identical no
	// matter which working directory invoked the generator: both
	// "internal/<module>/..." from the root and "../../internal/<module>/..."
	// from tools/contractgen name the same fragment.
	canonical := contractPath
	for strings.HasPrefix(canonical, "../") || strings.HasPrefix(canonical, "./") {
		canonical = strings.TrimPrefix(strings.TrimPrefix(canonical, "../"), "./")
	}
	return fmt.Sprintf(`// Code generated by tools/contractgen from %s. DO NOT EDIT.
// Source of truth: %s (staged fragment, not part of the published contract).
// Readonly by convention: every emitted member is readonly.
`, canonical, canonical)
}

// Render reads the contract at contractPath and returns the generated
// TypeScript source.
func Render(contractPath string) ([]byte, error) {
	data, err := os.ReadFile(contractPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", contractPath, err)
	}
	source, err := RenderBytes(data)
	if err != nil {
		return nil, err
	}
	if filepath.Base(contractPath) == "openapi.json" {
		return source, nil
	}
	return bytes.Replace(source, []byte(generatedHeader), []byte(headerFor(contractPath)), 1), nil
}

// RenderBytes renders the generated TypeScript source for a contract
// document already in memory.
func RenderBytes(data []byte) ([]byte, error) {
	var parsed document
	if err := json.Unmarshal(data, &parsed); err != nil {
		return nil, fmt.Errorf("invalid OpenAPI JSON: %w", err)
	}
	if len(parsed.Components.Schemas) == 0 {
		return nil, errors.New("components.schemas is empty: nothing to generate")
	}

	schemas := make(map[string]rawSchema, len(parsed.Components.Schemas))
	names := make([]string, 0, len(parsed.Components.Schemas))
	for name, raw := range parsed.Components.Schemas {
		if !identifierPattern.MatchString(name) {
			return nil, fmt.Errorf("components.schemas: %q is not a TypeScript identifier", name)
		}
		var schema rawSchema
		if err := json.Unmarshal(raw, &schema); err != nil {
			return nil, fmt.Errorf("components.schemas.%s: %w", name, err)
		}
		if len(schema) == 0 {
			return nil, fmt.Errorf("components.schemas.%s: empty schema", name)
		}
		schemas[name] = schema
		names = append(names, name)
	}
	sort.Strings(names)

	renderer := &typeRenderer{schemas: schemas}
	var out bytes.Buffer
	out.WriteString(generatedHeader)
	header, err := surfaceHeader(parsed.Paths)
	if err != nil {
		return nil, err
	}
	out.WriteString(header)
	for index, name := range names {
		interfaceSource, err := renderer.renderInterface(name, schemas[name], "components.schemas."+name)
		if err != nil {
			return nil, err
		}
		if index == 0 {
			out.WriteString("\n")
		}
		out.WriteString(interfaceSource)
		if index < len(names)-1 {
			out.WriteString("\n")
		}
	}
	return out.Bytes(), nil
}

// surfaceHeader binds transport provenance to HTML and JSON operations, even
// when a route addition does not change components.schemas. Canonical JSON
// keeps whitespace and object-key order from changing the fingerprint.
func surfaceHeader(paths map[string]any) (string, error) {
	if len(paths) == 0 {
		return "", nil
	}
	canonical, err := json.Marshal(paths)
	if err != nil {
		return "", fmt.Errorf("encode HTTP surface: %w", err)
	}
	return fmt.Sprintf("// HTTP surface SHA-256: %x\n", sha256.Sum256(canonical)), nil
}

// HasDrift reports whether the generated artifact on disk differs from
// source, or is missing. It never writes; make generate-check uses it to
// fail loudly on stale contracts.
func HasDrift(target string, source []byte) (bool, error) {
	existing, err := os.ReadFile(target)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return true, nil
		}
		return false, fmt.Errorf("read %s: %w", target, err)
	}
	return !bytes.Equal(existing, source), nil
}

// WriteIfChanged writes source to target only when it differs, so running
// the generator on a fresh checkout is a no-op.
func WriteIfChanged(target string, source []byte) (bool, error) {
	existing, err := os.ReadFile(target)
	if err == nil && bytes.Equal(existing, source) {
		return false, nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("read %s: %w", target, err)
	}
	directory := filepath.Dir(target)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return false, fmt.Errorf("create %s: %w", directory, err)
	}
	if err := os.WriteFile(target, source, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", target, err)
	}
	return true, nil
}

// typeRenderer resolves $ref against the very schemas being rendered.
type typeRenderer struct {
	schemas map[string]rawSchema
}

// renderInterface renders one top-level schema as a readonly interface.
// Transport entities of this contract are records, never bare scalars.
func (r *typeRenderer) renderInterface(name string, schema rawSchema, path string) (string, error) {
	if err := r.checkKeywords(schema, path); err != nil {
		return "", err
	}
	types, err := decodeTypes(schema, path)
	if err != nil {
		return "", err
	}
	if len(types) != 1 || types[0] != "object" {
		return "", fmt.Errorf("%s: top-level schemas must be `type: object` in the supported subset, found %s", path, describeTypes(types))
	}

	rawProperties, ok := schema["properties"]
	if !ok {
		return "", fmt.Errorf("%s: object schemas must declare properties", path)
	}
	var properties map[string]rawSchema
	if err := json.Unmarshal(rawProperties, &properties); err != nil {
		return "", fmt.Errorf("%s.properties: %w", path, err)
	}
	if len(properties) == 0 {
		return "", fmt.Errorf("%s: object schemas must declare at least one property", path)
	}

	required, err := decodeRequired(schema, path)
	if err != nil {
		return "", err
	}
	for _, propertyName := range sortedKeys(required) {
		if _, exists := properties[propertyName]; !exists {
			return "", fmt.Errorf("%s: required lists %q, which properties does not define", path, propertyName)
		}
	}

	names := sortedKeys(properties)
	var fields strings.Builder
	for _, propertyName := range names {
		if !identifierPattern.MatchString(propertyName) {
			return "", fmt.Errorf("%s.properties: %q is not a TypeScript identifier", path, propertyName)
		}
		expression, err := r.typeExpression(properties[propertyName], path+".properties."+propertyName)
		if err != nil {
			return "", err
		}
		optional := ""
		if !required[propertyName] {
			optional = "?"
		}
		fmt.Fprintf(&fields, "  readonly %s%s: %s;\n", propertyName, optional, expression)
	}
	return fmt.Sprintf("export interface %s {\n%s}\n", name, fields.String()), nil
}

// typeExpression renders any schema fragment as a TypeScript type.
func (r *typeRenderer) typeExpression(schema rawSchema, path string) (string, error) {
	if err := r.checkKeywords(schema, path); err != nil {
		return "", err
	}

	if raw, ok := schema["$ref"]; ok {
		// Documenting keywords may accompany a reference; anything that could
		// change the type may not, so the emitted alias cannot lie.
		for _, keyword := range sortedKeys(schema) {
			if keyword == "$ref" || ignoredKeywords[keyword] || strings.HasPrefix(keyword, "x-") {
				continue
			}
			return "", fmt.Errorf("%s: $ref cannot be combined with %q in the supported subset", path, keyword)
		}
		return r.resolveRef(raw, path)
	}

	types, err := decodeTypes(schema, path)
	if err != nil {
		return "", err
	}

	if raw, ok := schema["oneOf"]; ok {
		if len(types) > 0 {
			return "", fmt.Errorf("%s: oneOf cannot be combined with `type` in the supported subset", path)
		}
		if _, hasEnum := schema["enum"]; hasEnum {
			return "", fmt.Errorf("%s: oneOf cannot be combined with `enum` in the supported subset", path)
		}
		return r.renderUnion(raw, path)
	}

	if raw, ok := schema["enum"]; ok {
		return renderEnum(raw, types, path)
	}

	return r.renderType(types, schema, path)
}

// renderType renders a fragment described by its `type` keyword.
func (r *typeRenderer) renderType(types []string, schema rawSchema, path string) (string, error) {
	if len(types) == 0 {
		return "", fmt.Errorf("%s: fragment declares none of `type`, `$ref`, `enum` or `oneOf`", path)
	}

	nullable := false
	members := make([]string, 0, len(types))
	for _, name := range types {
		if name == "null" {
			nullable = true
			continue
		}
		expression, err := r.renderNamedType(name, schema, path)
		if err != nil {
			return "", err
		}
		members = append(members, expression)
	}
	if len(members) == 0 {
		return "null", nil
	}
	if len(members) > 1 {
		return "", fmt.Errorf("%s: type %s is not supported; only one type plus `null` is allowed", path, describeTypes(types))
	}
	if nullable {
		return members[0] + " | null", nil
	}
	return members[0], nil
}

// renderNamedType renders one named type of the `type` keyword.
func (r *typeRenderer) renderNamedType(name string, schema rawSchema, path string) (string, error) {
	switch name {
	case "string", "integer", "number", "boolean":
		return renderScalar(name, schema, path)
	case "array":
		return r.renderArray(schema, path)
	case "object":
		return "", fmt.Errorf("%s: nested object schemas are not supported; promote it to a named component in api/openapi.json", path)
	default:
		return "", fmt.Errorf("%s: type %q is outside the supported subset", path, name)
	}
}

// renderScalar renders a scalar type, mapping known formats onto the
// TypeScript types the frontend transports.
func renderScalar(name string, schema rawSchema, path string) (string, error) {
	rawFormat, hasFormat := schema["format"]
	if !hasFormat {
		switch name {
		case "string":
			return "string", nil
		case "boolean":
			return "boolean", nil
		default:
			return "number", nil
		}
	}

	var format string
	if err := json.Unmarshal(rawFormat, &format); err != nil {
		return "", fmt.Errorf("%s.format: %w", path, err)
	}
	switch name {
	case "string":
		if textFormats[format] {
			return "string", nil
		}
	case "integer", "number":
		if numberFormats[format] {
			return "number", nil
		}
	}
	return "", fmt.Errorf("%s: format %q is outside the supported subset for type %q", path, format, name)
}

// renderArray renders an array schema as a readonly array.
func (r *typeRenderer) renderArray(schema rawSchema, path string) (string, error) {
	rawItems, ok := schema["items"]
	if !ok {
		return "", fmt.Errorf("%s: array schemas must declare items", path)
	}
	if bytes.HasPrefix(bytes.TrimSpace(rawItems), []byte("[")) {
		return "", fmt.Errorf("%s: tuple items are outside the supported subset", path)
	}
	var items rawSchema
	if err := json.Unmarshal(rawItems, &items); err != nil {
		return "", fmt.Errorf("%s.items: %w", path, err)
	}
	element, err := r.typeExpression(items, path+".items")
	if err != nil {
		return "", err
	}
	return "ReadonlyArray<" + element + ">", nil
}

// renderUnion renders a oneOf as a TypeScript union, collapsing repeats.
func (r *typeRenderer) renderUnion(raw json.RawMessage, path string) (string, error) {
	var members []rawSchema
	if err := json.Unmarshal(raw, &members); err != nil {
		return "", fmt.Errorf("%s.oneOf: %w", path, err)
	}
	if len(members) == 0 {
		return "", fmt.Errorf("%s: oneOf must declare at least one member", path)
	}
	seen := make(map[string]bool, len(members))
	ordered := make([]string, 0, len(members))
	for index, member := range members {
		expression, err := r.typeExpression(member, fmt.Sprintf("%s.oneOf[%d]", path, index))
		if err != nil {
			return "", err
		}
		if seen[expression] {
			continue
		}
		seen[expression] = true
		ordered = append(ordered, expression)
	}
	if len(ordered) == 1 {
		return ordered[0], nil
	}
	return strings.Join(ordered, " | "), nil
}

// resolveRef resolves a $ref against the schemas being rendered, so a
// dangling reference fails instead of emitting an undefined type.
func (r *typeRenderer) resolveRef(raw json.RawMessage, path string) (string, error) {
	var reference string
	if err := json.Unmarshal(raw, &reference); err != nil {
		return "", fmt.Errorf("%s.$ref: %w", path, err)
	}
	name := strings.TrimPrefix(reference, schemaRefPrefix)
	if name == reference || name == "" {
		return "", fmt.Errorf("%s: $ref %q is outside the supported subset; only %s<Name> is supported", path, reference, schemaRefPrefix)
	}
	if _, ok := r.schemas[name]; !ok {
		return "", fmt.Errorf("%s: $ref %q points to an unknown schema", path, reference)
	}
	return name, nil
}

// checkKeywords rejects any keyword the generator cannot honour, in sorted
// order so the message is stable.
func (r *typeRenderer) checkKeywords(schema rawSchema, path string) error {
	for _, keyword := range sortedKeys(schema) {
		if supportedKeywords[keyword] || ignoredKeywords[keyword] || strings.HasPrefix(keyword, "x-") {
			continue
		}
		return fmt.Errorf("%s: OpenAPI keyword %q is outside the supported subset (see tools/contractgen)", path, keyword)
	}
	return nil
}

// renderEnum renders an enum as a union of literal types.
func renderEnum(raw json.RawMessage, types []string, path string) (string, error) {
	for _, name := range types {
		if name == "string" || name == "integer" || name == "number" {
			continue
		}
		return "", fmt.Errorf("%s: enum is only supported for string and number types, found %q", path, name)
	}

	var values []json.RawMessage
	if err := json.Unmarshal(raw, &values); err != nil {
		return "", fmt.Errorf("%s.enum: %w", path, err)
	}
	if len(values) == 0 {
		return "", fmt.Errorf("%s: enum must declare at least one value", path)
	}

	seen := make(map[string]bool, len(values))
	literals := make([]string, 0, len(values))
	for index, value := range values {
		literal, err := enumLiteral(value, fmt.Sprintf("%s.enum[%d]", path, index))
		if err != nil {
			return "", err
		}
		if seen[literal] {
			continue
		}
		seen[literal] = true
		literals = append(literals, literal)
	}
	if len(literals) == 1 {
		return literals[0], nil
	}
	return strings.Join(literals, " | "), nil
}

// enumLiteral renders one enum value as a TypeScript literal type. Only
// strings and numbers are supported: booleans and nulls are expressed with
// `type`, not `enum`.
func enumLiteral(raw json.RawMessage, path string) (string, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 {
		return "", fmt.Errorf("%s: empty enum value", path)
	}
	if trimmed[0] == '"' {
		var text string
		if err := json.Unmarshal(trimmed, &text); err != nil {
			return "", fmt.Errorf("%s: invalid string enum value: %w", path, err)
		}
		encoded, err := json.Marshal(text)
		if err != nil {
			return "", fmt.Errorf("%s: encode string enum value: %w", path, err)
		}
		return string(encoded), nil
	}
	var number json.Number
	decoder := json.NewDecoder(bytes.NewReader(trimmed))
	decoder.UseNumber()
	if err := decoder.Decode(&number); err != nil {
		return "", fmt.Errorf("%s: enum value %s is outside the supported subset (strings and numbers only)", path, trimmed)
	}
	return number.String(), nil
}

// decodeTypes decodes the optional `type` keyword.
func decodeTypes(schema rawSchema, path string) ([]string, error) {
	raw, ok := schema["type"]
	if !ok {
		return nil, nil
	}
	var types typeList
	if err := json.Unmarshal(raw, &types); err != nil {
		return nil, fmt.Errorf("%s.type: %w", path, err)
	}
	return types, nil
}

// decodeRequired decodes the optional `required` keyword as a set.
func decodeRequired(schema rawSchema, path string) (map[string]bool, error) {
	raw, ok := schema["required"]
	if !ok {
		return map[string]bool{}, nil
	}
	var listed []string
	if err := json.Unmarshal(raw, &listed); err != nil {
		return nil, fmt.Errorf("%s.required: %w", path, err)
	}
	required := make(map[string]bool, len(listed))
	for _, name := range listed {
		required[name] = true
	}
	return required, nil
}

// describeTypes renders the decoded `type` keyword for error messages.
func describeTypes(types []string) string {
	if len(types) == 0 {
		return "no type"
	}
	quoted := make([]string, 0, len(types))
	for _, name := range types {
		quoted = append(quoted, fmt.Sprintf("%q", name))
	}
	return strings.Join(quoted, ", ")
}

// sortedKeys returns the keys of any string-keyed map in stable order, so
// rendering (and error reporting) never depends on map iteration order.
func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
