// Tests of the contractgen renderer (P18-T02): the supported OpenAPI subset
// must render deterministic readonly TypeScript, anything outside the subset
// must fail with the keyword and path that carries it, and the committed
// artifact must match the versioned contract.
package main

import (
	"encoding/json"
	"regexp"
	"strings"
	"testing"
)

// fixtureContract exercises every construct of the supported subset plus the
// keywords the generator ignores on purpose.
const fixtureContract = `{
  "components": {
    "schemas": {
      "Zeta": {
        "type": "object",
        "required": ["b", "list"],
        "properties": {
          "list": {"type": "array", "items": {"$ref": "#/components/schemas/Alpha"}},
          "b": {"type": "string", "format": "date-time"},
          "a": {"type": "integer"},
          "described_ref": {"$ref": "#/components/schemas/Alpha", "description": "ignored"},
          "nullable": {"type": ["string", "null"]},
          "maybe": {"oneOf": [{"$ref": "#/components/schemas/Alpha"}, {"type": "null"}]},
          "state": {"type": "string", "enum": ["active", "closed", "active"]},
          "single": {"type": "string", "enum": ["only"]},
          "flag": {"type": "boolean"},
          "ratio": {"type": "number", "format": "double"},
          "nothing": {"type": "null"},
          "documented": {"type": "string", "description": "ignored", "maxLength": 10},
          "matrix": {"type": "array", "items": {"type": "array", "items": {"type": "boolean"}}}
        }
      },
      "Alpha": {
        "type": "object",
        "properties": {"id": {"type": "string", "format": "uuid"}}
      }
    }
  }
}`

// fixtureExpected is the exact artifact the fixture contract must produce:
// readonly members, arrays as ReadonlyArray, nullables as unions and
// ignored keywords leaving no trace.
const fixtureExpected = `// Code generated by tools/contractgen from api/openapi.json. DO NOT EDIT.
// Source of truth: api/openapi.json (the versioned HTTP contract).
// Readonly by convention: every emitted member is readonly.

export interface Alpha {
  readonly id?: string;
}

export interface Zeta {
  readonly a?: number;
  readonly b: string;
  readonly described_ref?: Alpha;
  readonly documented?: string;
  readonly flag?: boolean;
  readonly list: ReadonlyArray<Alpha>;
  readonly matrix?: ReadonlyArray<ReadonlyArray<boolean>>;
  readonly maybe?: Alpha | null;
  readonly nothing?: null;
  readonly nullable?: string | null;
  readonly ratio?: number;
  readonly single?: "only";
  readonly state?: "active" | "closed";
}
`

func TestSupportedSubsetRendersReadonlyTypeScript(t *testing.T) {
	t.Parallel()

	source, err := RenderBytes([]byte(fixtureContract))
	if err != nil {
		t.Fatalf("render fixture: %v", err)
	}
	if string(source) != fixtureExpected {
		t.Fatalf("rendered fixture differs from the expected artifact:\n--- got ---\n%s\n--- want ---\n%s", source, fixtureExpected)
	}
}

func TestHTMLRouteChangesRegenerateTransportProvenance(t *testing.T) {
	var doc map[string]any
	if err := json.Unmarshal([]byte(tinyContract), &doc); err != nil {
		t.Fatal(err)
	}
	doc["paths"] = map[string]any{"/login": map[string]any{"get": map[string]any{"operationId": "getLogin"}}}
	before, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	first, err := RenderBytes(before)
	if err != nil {
		t.Fatal(err)
	}
	doc["paths"].(map[string]any)["/"] = map[string]any{"get": map[string]any{"operationId": "getRealmHome"}}
	after, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	second, err := RenderBytes(after)
	if err != nil {
		t.Fatal(err)
	}
	if string(first) == string(second) || !strings.Contains(string(second), "// HTTP surface SHA-256:") {
		t.Fatal("HTML route change did not update generated transport provenance")
	}
	withoutFingerprint := regexp.MustCompile(`(?m)^// HTTP surface SHA-256: [a-f0-9]+\n`)
	if string(withoutFingerprint.ReplaceAll(first, nil)) != string(withoutFingerprint.ReplaceAll(second, nil)) {
		t.Fatal("route-only change modified transport types")
	}
	pretty, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	third, err := RenderBytes(pretty)
	if err != nil {
		t.Fatal(err)
	}
	if string(second) != string(third) {
		t.Fatal("fingerprint depends on document whitespace")
	}
}

func TestRenderIsDeterministicAndOrderIndependent(t *testing.T) {
	t.Parallel()

	// Same document, keys declared in a different order: the artifact must
	// not depend on map iteration order anywhere.
	reordered := `{
  "components": {
    "schemas": {
      "Alpha": {
        "properties": {"id": {"format": "uuid", "type": "string"}},
        "type": "object"
      },
      "Zeta": {
        "properties": {
          "state": {"enum": ["active", "closed", "active"], "type": "string"},
          "list": {"items": {"$ref": "#/components/schemas/Alpha"}, "type": "array"},
          "a": {"type": "integer"},
          "b": {"format": "date-time", "type": "string"},
          "matrix": {"type": "array", "items": {"type": "array", "items": {"type": "boolean"}}},
          "flag": {"type": "boolean"},
          "single": {"enum": ["only"], "type": "string"},
          "ratio": {"format": "double", "type": "number"},
          "nullable": {"type": ["string", "null"]},
          "documented": {"description": "ignored", "maxLength": 10, "type": "string"},
          "described_ref": {"description": "ignored", "$ref": "#/components/schemas/Alpha"},
          "maybe": {"oneOf": [{"$ref": "#/components/schemas/Alpha"}, {"type": "null"}]},
          "nothing": {"type": "null"}
        },
        "required": ["b", "list"],
        "type": "object"
      }
    }
  }
}`

	first, err := RenderBytes([]byte(fixtureContract))
	if err != nil {
		t.Fatalf("render fixture: %v", err)
	}
	second, err := RenderBytes([]byte(fixtureContract))
	if err != nil {
		t.Fatalf("render fixture again: %v", err)
	}
	if string(first) != string(second) {
		t.Fatal("rendering the same contract twice produced different artifacts")
	}
	third, err := RenderBytes([]byte(reordered))
	if err != nil {
		t.Fatalf("render reordered fixture: %v", err)
	}
	if string(first) != string(third) {
		t.Fatalf("artifact depends on key order:\n--- first ---\n%s\n--- reordered ---\n%s", first, third)
	}
}

func TestRealContractRendersDeterministically(t *testing.T) {
	t.Parallel()

	var previous string
	for attempt := 0; attempt < 5; attempt++ {
		source, err := Render("../../api/openapi.json")
		if err != nil {
			t.Fatalf("render contract: %v", err)
		}
		if attempt > 0 && string(source) != previous {
			t.Fatalf("rendering the contract is not deterministic (attempt %d)", attempt)
		}
		previous = string(source)
	}

	// The artifact must not fall back to `any`: a missing mapping would be
	// silently untyped instead of failing the build.
	if match := regexp.MustCompile(`\bany\b`).FindString(previous); match != "" {
		t.Fatalf("generated artifact contains %q", match)
	}
	for _, line := range strings.Split(previous, "\n") {
		if !strings.HasPrefix(line, "  ") {
			continue
		}
		if !strings.Contains(line, "readonly ") {
			t.Errorf("generated member is not readonly: %q", line)
		}
	}
}

func TestCommittedArtifactMatchesTheContract(t *testing.T) {
	t.Parallel()

	source, err := Render("../../api/openapi.json")
	if err != nil {
		t.Fatalf("render contract: %v", err)
	}
	drifted, err := HasDrift("../../web/src/contracts/generated.ts", source)
	if err != nil {
		t.Fatalf("compare artifact: %v", err)
	}
	if drifted {
		t.Fatal("web/src/contracts/generated.ts is stale; run 'make generate'")
	}
}

func TestStagedArtifactsMatchTheirFragments(t *testing.T) {
	t.Parallel()

	// P56-T01: every staged transport is reproduced from its fragment by
	// the same renderer, so drift in either side fails here and in the
	// directed `contractgen -check -contract FILE -out FILE` runs.
	pairs := map[string]string{
		"../../internal/seasons/adapters/http/openapi.fragment.json":  "../../web/src/contracts/staged/seasons.ts",
		"../../internal/metering/adapters/http/openapi.fragment.json": "../../web/src/contracts/staged/metering.ts",
		"../../internal/commerce/adapters/http/openapi.fragment.json": "../../web/src/contracts/staged/commerce.ts",
		"../../internal/disputes/adapters/http/openapi.fragment.json": "../../web/src/contracts/staged/disputes.ts",
	}
	for contract, artifact := range pairs {
		source, err := Render(contract)
		if err != nil {
			t.Fatalf("render %s: %v", contract, err)
		}
		drifted, err := HasDrift(artifact, source)
		if err != nil {
			t.Fatalf("compare %s: %v", artifact, err)
		}
		if drifted {
			t.Fatalf("%s is stale for %s; regenerate with contractgen", artifact, contract)
		}
	}
}

func TestUnsupportedConstructsFailWithKeywordAndPath(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name     string
		contract string
		want     []string
	}{
		{
			name:     "allOf",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"allOf":[{"type":"string"}]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `"allOf"`},
		},
		{
			name:     "anyOf",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"anyOf":[{"type":"string"}]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `"anyOf"`},
		},
		{
			name:     "additionalProperties",
			contract: `{"components":{"schemas":{"A":{"type":"object","additionalProperties":false,"properties":{"x":{"type":"string"}}}}}}`,
			want:     []string{"components.schemas.A", `"additionalProperties"`},
		},
		{
			name:     "const",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"const":"fixed","type":"string"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `"const"`},
		},
		{
			name:     "discriminator",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"discriminator":{"propertyName":"k"},"oneOf":[{"type":"string"}]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `"discriminator"`},
		},
		{
			name:     "nested object",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"object","properties":{"y":{"type":"string"}}}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "nested object schemas are not supported"},
		},
		{
			name:     "tuple items",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"array","items":[{"type":"string"}]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "tuple items"},
		},
		{
			name:     "array without items",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"array"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "must declare items"},
		},
		{
			name:     "unknown format",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"string","format":"binary-bytes"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `format "binary-bytes" is outside the supported subset`},
		},
		{
			name:     "dangling ref",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"$ref":"#/components/schemas/Missing"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "points to an unknown schema"},
		},
		{
			name:     "foreign ref",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"$ref":"#/components/responses/Nope"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "outside the supported subset"},
		}, {
			name:     "ref with a type-changing sibling",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"$ref":"#/components/schemas/B","type":"string"}}},"B":{"type":"object","properties":{"y":{"type":"string"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `$ref cannot be combined with "type" in the supported subset`},
		},
		{
			name:     "oneOf with type",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"string","oneOf":[{"type":"string"}]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "oneOf cannot be combined with `type`"},
		},
		{
			name:     "oneOf with enum",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"enum":["a"],"oneOf":[{"type":"string"}]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "oneOf cannot be combined with `enum`"},
		},
		{
			name:     "empty oneOf",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"oneOf":[]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "oneOf must declare at least one member"},
		},
		{
			name:     "boolean enum value",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"string","enum":["ok",true]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x.enum[1]", "outside the supported subset"},
		},
		{
			name:     "enum on object type",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"object","enum":["a"],"properties":{"y":{"type":"string"}}}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "enum is only supported for string and number types"},
		},
		{
			name:     "no type at all",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "declares none of `type`, `$ref`, `enum` or `oneOf`"},
		},
		{
			name:     "multiple types",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":["string","integer"]}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", "only one type plus `null` is allowed"},
		},
		{
			name:     "untyped type keyword",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":{"nested":true}}}}}}}`,
			want:     []string{"components.schemas.A.properties.x.type", "must be a string or an array of strings"},
		},
		{
			name:     "required not defined",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"string"}},"required":["y"]}}}}`,
			want:     []string{"components.schemas.A", `required lists "y"`},
		},
		{
			name:     "schema without properties",
			contract: `{"components":{"schemas":{"A":{"type":"object"}}}}`,
			want:     []string{"components.schemas.A", "must declare properties"},
		},
		{
			name:     "empty properties",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{}}}}}`,
			want:     []string{"components.schemas.A", "must declare at least one property"},
		},
		{
			name:     "top-level scalar",
			contract: `{"components":{"schemas":{"A":{"type":"string"}}}}`,
			want:     []string{"components.schemas.A", "top-level schemas must be `type: object`"},
		},
		{
			name:     "schema name not an identifier",
			contract: `{"components":{"schemas":{"A-B":{"type":"object","properties":{"x":{"type":"string"}}}}}}`,
			want:     []string{"components.schemas", `"A-B" is not a TypeScript identifier`},
		},
		{
			name:     "property name not an identifier",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"a-b":{"type":"string"}}}}}}`,
			want:     []string{"components.schemas.A.properties", `"a-b" is not a TypeScript identifier`},
		},
		{
			name:     "unknown type",
			contract: `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"binary"}}}}}}`,
			want:     []string{"components.schemas.A.properties.x", `type "binary" is outside the supported subset`},
		},
		{
			name:     "empty schemas",
			contract: `{"components":{"schemas":{}}}`,
			want:     []string{"components.schemas is empty"},
		},
		{
			name:     "empty schema",
			contract: `{"components":{"schemas":{"A":{}}}}`,
			want:     []string{"components.schemas.A", "empty schema"},
		},
		{
			name:     "invalid json",
			contract: `{"components":`,
			want:     []string{"invalid OpenAPI JSON"},
		},
		{
			name:     "no components",
			contract: `{}`,
			want:     []string{"components.schemas is empty"},
		},
	}

	for _, testCase := range cases {
		testCase := testCase
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			source, err := RenderBytes([]byte(testCase.contract))
			if err == nil {
				t.Fatalf("RenderBytes succeeded, want failure; artifact:\n%s", source)
			}
			for _, fragment := range testCase.want {
				if !strings.Contains(err.Error(), fragment) {
					t.Errorf("error %q does not mention %q", err, fragment)
				}
			}
		})
	}
}

func TestIgnoredKeywordsDoNotChangeTheArtifact(t *testing.T) {
	t.Parallel()

	plain := `{"components":{"schemas":{"A":{"type":"object","properties":{"x":{"type":"string"}}}}}}`
	documented := `{"components":{"schemas":{"A":{"description":"doc","title":"A","x-internal":true,"type":"object","properties":{"x":{"type":"string","description":"doc","examples":["sample"],"default":"s","deprecated":false,"readOnly":true,"writeOnly":false,"pattern":"^a$","minLength":1,"maxLength":9,"minProperties":0,"maxProperties":9,"x-note":"n"}}}}}}`

	first, err := RenderBytes([]byte(plain))
	if err != nil {
		t.Fatalf("render plain: %v", err)
	}
	second, err := RenderBytes([]byte(documented))
	if err != nil {
		t.Fatalf("render documented: %v", err)
	}
	if string(first) != string(second) {
		t.Fatalf("documentation keywords changed the artifact:\n--- plain ---\n%s\n--- documented ---\n%s", first, second)
	}
}
