// Deterministic emission of the generated artifacts (P02-T07):
// TypeScript keys for the frontend and an embedded Go catalog for HTML and
// emails, per I18N_STANDARD.md section 3. Same input -> byte-identical
// output, proven by tests and by make generate-check.
package i18ngen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Outputs describes where the generated artifacts live.
type Outputs struct {
	// TSTarget is the TypeScript file emitted for the frontend.
	TSTarget string

	// GoTarget is the Go catalog file emitted for HTML and emails.
	GoTarget string

	// GOPackage is the package clause of the Go catalog.
	GOPackage string
}

// Generate renders both artifacts from the validated bundle.
func Generate(bundle *Bundle, outputs Outputs) (tsSource []byte, goSource []byte, err error) {
	browser := browserBundle(bundle)
	if len(browser.Namespaces) == 0 {
		return nil, nil, fmt.Errorf("i18ngen: at least one browser namespace is required")
	}
	tsSource, err = renderTS(browser)
	if err != nil {
		return nil, nil, err
	}
	goSource, err = renderGo(bundle, outputs.GOPackage)
	if err != nil {
		return nil, nil, err
	}
	return tsSource, goSource, nil
}

// browserBundle keeps server-* namespaces in the validated Go catalog only.
// SSR text does not belong in every browser page's initial translation payload.
// Both catalogs still share the same duplicate/key/placeholder parity checks.
func browserBundle(bundle *Bundle) *Bundle {
	browser := &Bundle{Messages: bundle.Messages, Placeholders: bundle.Placeholders}
	for _, namespace := range bundle.Namespaces {
		if !strings.HasPrefix(namespace, "server-") {
			browser.Namespaces = append(browser.Namespaces, namespace)
		}
	}
	return browser
}

// RenderAll loads the bundle at root and renders both artifacts.
func RenderAll(root string, outputs Outputs) (tsSource []byte, goSource []byte, err error) {
	bundle, err := LoadBundle(root)
	if err != nil {
		return nil, nil, err
	}
	return Generate(bundle, outputs)
}

// HasDrift reports whether any generated artifact on disk differs from
// the freshly rendered source. It never writes; make generate-check uses
// it to fail loudly on stale artifacts.
func HasDrift(outputs Outputs, tsSource, goSource []byte) (bool, error) {
	for _, candidate := range []struct {
		target string
		source []byte
	}{{outputs.TSTarget, tsSource}, {outputs.GoTarget, goSource}} {
		existing, err := os.ReadFile(candidate.target)
		if err != nil {
			if os.IsNotExist(err) {
				return true, nil
			}
			return false, fmt.Errorf("i18ngen: read %s: %w", candidate.target, err)
		}
		if string(existing) != string(candidate.source) {
			return true, nil
		}
	}
	return false, nil
}

// WriteIfChanged writes source only when it differs from the file at
// target, so running the generator is always a no-op on fresh checkouts and
// generate-check can detect drift by diffing.
func WriteIfChanged(target string, source []byte) (changed bool, err error) {
	existing, readErr := os.ReadFile(target)
	if readErr == nil && string(existing) == string(source) {
		return false, nil
	}
	if readErr != nil && !os.IsNotExist(readErr) {
		return false, fmt.Errorf("i18ngen: read %s: %w", target, readErr)
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return false, fmt.Errorf("i18ngen: create directory for %s: %w", target, err)
	}
	if err := os.WriteFile(target, source, 0o644); err != nil {
		return false, fmt.Errorf("i18ngen: write %s: %w", target, err)
	}
	return true, nil
}

// keysOf returns the sorted keys of one namespace.
func (bundle *Bundle) keysOf(namespace string) []string {
	keys := make([]string, 0, len(bundle.Messages[namespace]))
	for key := range bundle.Messages[namespace] {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// renderTS emits the frontend artifact: the namespace list, the key union,
// per-locale messages and placeholder metadata. Deterministic: keys are
// sorted and the output never embeds timestamps.
//
// The per-namespace key arrays lived here until P58-T04, when pages/arena.js
// broke the 50 KB initial budget of docs/FRONTEND.md section 11: the key
// list cost ~3.7 KB compressed on every page while its only runtime reader
// counted namespaces. The key union type below keeps compile-time safety;
// the runtime keeps the namespace list alone.
func renderTS(bundle *Bundle) ([]byte, error) {
	var body strings.Builder
	body.WriteString("// Code generated by internal/i18ngen from locales/. DO NOT EDIT.\n")
	body.WriteString("// Source of truth: locales/<locale>/<namespace>.json (I18N_STANDARD.md).\n\n")

	body.WriteString("/** Namespaces in the bundle: the only runtime list the translator needs. */\n")
	body.WriteString("export const namespaces = [\n")
	for _, namespace := range bundle.Namespaces {
		body.WriteString(fmt.Sprintf("  %q,\n", namespace))
	}
	body.WriteString("] as const;\n\n")

	body.WriteString("/** Every message key across namespaces. */\n")
	body.WriteString("export type MessageKey =\n")
	for _, namespace := range bundle.Namespaces {
		for _, key := range bundle.keysOf(namespace) {
			body.WriteString(fmt.Sprintf("  | %q\n", key))
		}
	}
	body.WriteString(";\n\n")

	// The placeholder map is emitted with literal types (P18-T09) on purpose: the
	// frontend translator derives, per key, which named values a message accepts,
	// so `translate("auth.errors.weak_password", { min: 8 })` compiles and the
	// same call without `min` does not. The `satisfies` clause keeps that
	// precision without giving up the invariant that every entry is a list of
	// names.
	body.WriteString("/** Named placeholders per message key: the exact values one translation accepts. */\n")
	body.WriteString("export const messagePlaceholders = Object.freeze({\n")
	for _, namespace := range bundle.Namespaces {
		for _, key := range bundle.keysOf(namespace) {
			quoted := make([]string, 0, len(bundle.Placeholders[namespace][key]))
			for _, name := range bundle.Placeholders[namespace][key] {
				quoted = append(quoted, fmt.Sprintf("%q", name))
			}
			body.WriteString(fmt.Sprintf("  %q: [%s],\n", key, strings.Join(quoted, ", ")))
		}
	}
	body.WriteString("} as const satisfies Readonly<Record<string, readonly string[]>>);\n\n")

	body.WriteString("/** Localized messages per locale per key. */\n")
	body.WriteString("export const messages: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.freeze({\n")
	for _, locale := range SupportedLocales {
		body.WriteString(fmt.Sprintf("  %q: Object.freeze({\n", locale))
		for _, namespace := range bundle.Namespaces {
			for _, key := range bundle.keysOf(namespace) {
				body.WriteString(fmt.Sprintf("    %q: %q,\n", key, bundle.Messages[namespace][key][locale]))
			}
		}
		body.WriteString("  }),\n")
	}
	body.WriteString("});\n")

	return []byte(body.String()), nil
}

// renderGo emits the embedded Go catalog used by HTML and email adapters.
func renderGo(bundle *Bundle, packageName string) ([]byte, error) {
	var body strings.Builder
	body.WriteString("// Code generated by internal/i18ngen from locales/. DO NOT EDIT.\n")
	body.WriteString("// Source of truth: locales/<locale>/<namespace>.json (I18N_STANDARD.md).\n\n")
	body.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	body.WriteString("// catalog maps locale -> message key -> localized message.\n")
	body.WriteString("var catalog = map[string]map[string]string{\n")
	for _, locale := range SupportedLocales {
		body.WriteString(fmt.Sprintf("\t%q: {\n", locale))
		for _, namespace := range bundle.Namespaces {
			for _, key := range bundle.keysOf(namespace) {
				body.WriteString(fmt.Sprintf("\t\t%q: %q,\n", key, bundle.Messages[namespace][key][locale]))
			}
		}
		body.WriteString("\t},\n")
	}
	body.WriteString("}\n\n")

	body.WriteString("// placeholders maps message key -> sorted placeholder names.\n")
	body.WriteString("var placeholders = map[string][]string{\n")
	for _, namespace := range bundle.Namespaces {
		for _, key := range bundle.keysOf(namespace) {
			names := bundle.Placeholders[namespace][key]
			quoted := make([]string, 0, len(names))
			for _, name := range names {
				quoted = append(quoted, fmt.Sprintf("%q", name))
			}
			body.WriteString(fmt.Sprintf("\t%q: {%s},\n", key, strings.Join(quoted, ", ")))
		}
	}
	body.WriteString("}\n")

	// Emitted Go must be gofmt-clean: make fmt-check gates the whole tree.
	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		return nil, fmt.Errorf("i18ngen: generated Go does not parse: %w", err)
	}
	return formatted, nil
}
