package auditkit

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

// The shared scaffolding is exercised end to end by the two gates that use it —
// their fixtures prove every family through these functions —, and what this file
// adds is the contract by itself: the vocabulary a gate is held to, the walk that
// decides what a gate looks at, and the ordering that makes two runs comparable.

func TestRuleKnownHoldsAGateToItsTable(t *testing.T) {
	rules := []Rule{{Name: "one", Reason: "porque sim"}, {Name: "two", Reason: "porque não"}}
	for _, entry := range rules {
		if !RuleKnown(rules, entry.Name) {
			t.Errorf("RuleKnown(rules, %q) = false", entry.Name)
		}
	}
	if RuleKnown(rules, "three") {
		t.Error("RuleKnown accepted a rule outside the table")
	}
}

func TestIsGeneratedReadsTheMarkerBeforeThePackage(t *testing.T) {
	const marked = "// Code generated by the sqlc of this repository. DO NOT EDIT.\n\npackage fixture\n"
	const decoy = "package fixture\n\n// Code generated by the sqlc of this repository. DO NOT EDIT.\n"
	const quoted = "package fixture\n\nconst notice = \"// Code generated by x DO NOT EDIT.\"\n"
	cases := []struct {
		name string
		text string
		want bool
	}{
		{"o marcador antes da cláusula exclui", marked, true},
		{"o marcador depois da cláusula é um comentário qualquer", decoy, false},
		{"o marcador dentro de uma string não exclui", quoted, false},
	}
	for _, entry := range cases {
		parsed, err := parser.ParseFile(token.NewFileSet(), "fixture.go", entry.text, parser.ParseComments)
		if err != nil {
			t.Fatalf("%s: ParseFile = %v", entry.name, err)
		}
		if got := IsGenerated(parsed); got != entry.want {
			t.Errorf("%s: IsGenerated = %v, want %v", entry.name, got, entry.want)
		}
	}
}

// TestGoFilesSkipsAndOrders is the walk's contract: the directories a gate names
// are not entered — that is how a fixture survives inside the tree as a file the
// gate refuses — and the answer is ordered, because two runs of a gate that
// answers in a different order are two gates.
func TestGoFilesSkipsAndOrders(t *testing.T) {
	root := t.TempDir()
	write := func(relative string) {
		path := filepath.Join(root, relative)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", relative, err)
		}
		if err := os.WriteFile(path, []byte("package fixture\n"), 0o644); err != nil {
			t.Fatalf("write %s: %v", relative, err)
		}
	}
	write("b/second.go")
	write("a/first.go")
	write("a/notes.md")
	write("testdata/refused/fixture.go")
	write("vendor/dependency.go")

	files, err := GoFiles(root, SkippedDirectories)
	if err != nil {
		t.Fatalf("GoFiles = %v", err)
	}
	// The walk answers with the paths it was given, so a tree walked from the
	// repository root answers in relative paths. The comparison is made the same
	// way here.
	relative := func(paths []string) []string {
		answer := make([]string, 0, len(paths))
		for _, path := range paths {
			stripped, err := filepath.Rel(root, path)
			if err != nil {
				t.Fatalf("Rel(%s) = %v", path, err)
			}
			answer = append(answer, filepath.ToSlash(stripped))
		}
		return answer
	}
	want := []string{"a/first.go", "b/second.go"}
	got := relative(files)
	if len(got) != len(want) {
		t.Fatalf("GoFiles = %v, want %v", got, want)
	}
	for index, entry := range want {
		if got[index] != entry {
			t.Fatalf("GoFiles = %v, want %v", got, want)
		}
	}

	entered, err := GoFiles(root, nil)
	if err != nil {
		t.Fatalf("GoFiles without the skip list = %v", err)
	}
	if len(entered) != len(files)+2 {
		t.Fatalf("without the skip list GoFiles answered %v: a fixture and a vendor file are what the list holds back", entered)
	}
}

func TestSortFindingsIsTotal(t *testing.T) {
	findings := []Finding{
		{Rule: "rule-b", Path: "b.go", Line: 2},
		{Rule: "rule-b", Path: "a.go", Line: 9},
		{Rule: "rule-a", Path: "a.go", Line: 9},
	}
	SortFindings(findings)
	want := []Finding{
		{Rule: "rule-a", Path: "a.go", Line: 9},
		{Rule: "rule-b", Path: "a.go", Line: 9},
		{Rule: "rule-b", Path: "b.go", Line: 2},
	}
	for index, entry := range want {
		if findings[index].Path != entry.Path || findings[index].Rule != entry.Rule {
			t.Fatalf("SortFindings = %v, want %v", findings, want)
		}
	}
	if got := findings[0].String(); got != "a.go:9: rule-a: " {
		t.Errorf("Finding.String() = %q", got)
	}
}
