package http

import (
	"errors"
	"net/http"

	"github.com/AlexandreZanata/Regnovum/internal/platform/apperr"
	"github.com/AlexandreZanata/Regnovum/internal/platform/httperror"
	"github.com/AlexandreZanata/Regnovum/internal/platform/security"
	"github.com/AlexandreZanata/Regnovum/internal/ports"
	"github.com/AlexandreZanata/Regnovum/internal/profiles/application"
	"github.com/AlexandreZanata/Regnovum/internal/profiles/domain"
)

// exportFilename is the fixed download filename; it carries no
// request-controlled value.
const exportFilename = "regnovum-personal-export.json"

// ExportHandlerConfig aggregates the personal export use cases and the
// session freshness port required to serve the export API.
type ExportHandlerConfig struct {
	RequestUseCase  *application.RequestPersonalExportUseCase
	DownloadUseCase *application.DownloadPersonalExportUseCase
	Sessions        application.SessionAgeDirectory
	SecurityManager *security.Manager
	Clock           ports.Clock
}

// ExportHandler serves the authenticated personal data export.
type ExportHandler struct {
	request  *application.RequestPersonalExportUseCase
	download *application.DownloadPersonalExportUseCase
	sessions application.SessionAgeDirectory
	security *security.Manager
	clock    ports.Clock
}

// NewExportHandler constructs the personal export HTTP handler.
func NewExportHandler(cfg ExportHandlerConfig) *ExportHandler {
	return &ExportHandler{
		request:  cfg.RequestUseCase,
		download: cfg.DownloadUseCase,
		sessions: cfg.Sessions,
		security: cfg.SecurityManager,
		clock:    cfg.Clock,
	}
}

// personalExportJobResponse is the accepted export job. The raw download
// token is returned exactly once: only its hash is persisted.
type personalExportJobResponse struct {
	ExportID      string `json:"export_id"`
	Status        string `json:"status"`
	DownloadToken string `json:"download_token"`
}

// RequestExport handles POST /api/v1/me/exports. The owner must have
// authenticated recently (step-up) and receives a single-use download link;
// the document itself is generated by the export job.
func (h *ExportHandler) RequestExport(w http.ResponseWriter, r *http.Request) {
	setPrivateNoStoreHeaders(w)

	identity, ok := security.FromContext(r.Context())
	if !ok {
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindUnauthorized, "unauthorized", "authentication required"))
		return
	}
	if h.request == nil {
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindInternal, "server_error", "personal export unavailable"))
		return
	}
	if !h.stepUpSatisfied(w, r, identity.SessionID) {
		return
	}

	result, err := h.request.Execute(r.Context(), domain.AccountID(identity.AccountID))
	if err != nil {
		writeExportProblem(w, r, err)
		return
	}
	writeJSON(w, http.StatusAccepted, personalExportJobResponse{
		ExportID:      result.ExportID,
		Status:        string(result.Status),
		DownloadToken: result.DownloadToken,
	})
}

// DownloadExport handles GET /api/v1/me/exports/{id}/download. The owner
// session and the opaque token are both required; an expired, exhausted or
// replayed link answers not found and never serves the document twice.
func (h *ExportHandler) DownloadExport(w http.ResponseWriter, r *http.Request) {
	setPrivateNoStoreHeaders(w)

	identity, ok := security.FromContext(r.Context())
	if !ok {
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindUnauthorized, "unauthorized", "authentication required"))
		return
	}
	if h.download == nil {
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindInternal, "server_error", "personal export unavailable"))
		return
	}

	result, err := h.download.Execute(r.Context(), application.DownloadPersonalExportCommand{
		AccountID: domain.AccountID(identity.AccountID),
		ExportID:  r.PathValue("id"),
		Token:     r.URL.Query().Get("token"),
	})
	if err != nil {
		writeExportProblem(w, r, err)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Content-Disposition", `attachment; filename="`+exportFilename+`"`)
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(result.Document)
}

// stepUpSatisfied enforces the export step-up rule from the server-observed
// session age. Unknown sessions deny like stale ones.
func (h *ExportHandler) stepUpSatisfied(w http.ResponseWriter, r *http.Request, sessionID string) bool {
	if h.sessions == nil || h.clock == nil {
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindInternal, "server_error", "session freshness unavailable"))
		return false
	}
	age, err := h.sessions.SessionAgeAt(r.Context(), sessionID, h.clock.Now())
	if err != nil {
		writeExportProblem(w, r, err)
		return false
	}
	if !domain.StepUpSatisfied(age) {
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindUnauthorized, "step_up_required", "recent authentication required"))
		return false
	}
	return true
}

// writeExportProblem maps export errors to RFC 9457 Problem Details with
// stable codes. Unknown, foreign, unavailable and replayed exports collapse
// into the same not-found code, so no oracle distinguishes them.
func writeExportProblem(w http.ResponseWriter, r *http.Request, err error) {
	switch {
	case errors.Is(err, domain.ErrEmptyAccountID):
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindUnauthorized, "unauthorized", "authentication required"))
	case errors.Is(err, application.ErrUnknownSession):
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindUnauthorized, "step_up_required", "recent authentication required"))
	case errors.Is(err, application.ErrInvalidExportToken):
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindForbidden, "invalid_export_token", "the export token is invalid"))
	case errors.Is(err, application.ErrExportNotFound),
		errors.Is(err, application.ErrExportUnavailable):
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindNotFound, "export_not_found", "personal export not found"))
	case errors.Is(err, application.ErrAccountNotEligible):
		_ = httperror.WriteProblem(w, r, apperr.New(apperr.KindForbidden, "account_not_eligible", "account is not eligible for this operation"))
	default:
		_ = httperror.WriteProblem(w, r, err)
	}
}

// RegisterRoutes wires the export endpoints into the provided ServeMux.
// Both routes require the owner session and the private cache policy.
func (h *ExportHandler) RegisterRoutes(mux *http.ServeMux) {
	request := http.Handler(http.HandlerFunc(h.RequestExport))
	download := http.Handler(http.HandlerFunc(h.DownloadExport))
	if h.security != nil {
		request = h.security.RequireAuthMiddleware()(request)
		download = h.security.RequireAuthMiddleware()(download)
	}
	mux.Handle("POST /api/v1/me/exports", withPrivateNoStore(request))
	mux.Handle("GET /api/v1/me/exports/{id}/download", withPrivateNoStore(download))
}
