// Package decoy is the other direction of the provenance probe: it carries the
// generated marker inside a string, the way the generators of this repository
// do, and it is product code. A gate that scanned the bytes would exclude it and
// never judge the function below; the gate reads the comments before the package
// clause, so it judges it and refuses it.
package decoy

// marker is the text a generator emits. Here it is a value.
const marker = "// Code generated by internal/i18ngen from locales/. DO NOT EDIT."

// mentionedButJudged exists to be refused.
func mentionedButJudged(value int) int {
	if value == 0 {
		value = 0
	}
	if value == 1 {
		value = 1
	}
	if value == 2 {
		value = 2
	}
	if value == 3 {
		value = 3
	}
	if value == 4 {
		value = 4
	}
	if value == 5 {
		value = 5
	}
	if value == 6 {
		value = 6
	}
	if value == 7 {
		value = 7
	}
	if value == 8 {
		value = 8
	}
	if value == 9 {
		value = 9
	}
	if value == 10 {
		value = 10
	}
	if value == 11 {
		value = 11
	}
	if value == 12 {
		value = 12
	}
	if value == 13 {
		value = 13
	}
	if value == 14 {
		value = 14
	}
	if value == 15 {
		value = 15
	}
	if value == 16 {
		value = 16
	}
	if value == 17 {
		value = 17
	}
	if value == 18 {
		value = 18
	}
	if value == 19 {
		value = 19
	}
	if value == 20 {
		value = 20
	}
	if value == 21 {
		value = 21
	}
	if value == 22 {
		value = 22
	}
	if value == 23 {
		value = 23
	}
	if value == 24 {
		value = 24
	}
	if value == 25 {
		value = 25
	}
	if value == 26 {
		value = 26
	}
	if value == 27 {
		value = 27
	}
	if value == 28 {
		value = 28
	}
	if value == 29 {
		value = 29
	}
	return value
}
