// Code generated by tools/contractgen from internal/commerce/adapters/http/openapi.fragment.json. DO NOT EDIT.
// Source of truth: internal/commerce/adapters/http/openapi.fragment.json (staged fragment, not part of the published contract).
// Readonly by convention: every emitted member is readonly.

export interface TradeReceipt {
  readonly contract_id: string;
  readonly contract_key: string;
  readonly escrow_transfer_id: string;
  readonly expires_at: string;
  readonly gross_milli: number;
  readonly net_milli: number;
  readonly object: string;
  readonly posted_at: string;
  readonly refunded_milli: number;
  readonly refunds: ReadonlyArray<TradeRefund>;
  readonly role: string;
  readonly settled_at?: string;
  readonly settlement_transfer_id?: string;
  readonly status: string;
  readonly tithe_milli: number;
  readonly title: string;
}

export interface TradeRefund {
  readonly amount_milli: number;
  readonly obligation_milli: number;
  readonly posted_at: string;
  readonly provider_share_milli: number;
  readonly refund_key: string;
  readonly tithe_reversal_milli: number;
}

export interface TradeStatement {
  readonly entries: ReadonlyArray<TradeStatementEntry>;
  readonly title: string;
}

export interface TradeStatementEntry {
  readonly contract_id: string;
  readonly contract_key: string;
  readonly gross_milli: number;
  readonly posted_at: string;
  readonly role: string;
  readonly status: string;
}
