// Code generated by tools/contractgen from internal/disputes/adapters/http/openapi.fragment.json. DO NOT EDIT.
// Source of truth: internal/disputes/adapters/http/openapi.fragment.json (staged fragment, not part of the published contract).
// Readonly by convention: every emitted member is readonly.

export interface PrivateCaseAppealInput {
  readonly reason: string;
}

export interface PrivateCaseDefenseInput {
  readonly digest: string;
}

export interface PrivateCaseFile {
  readonly accepts: number;
  readonly appeal_due_at?: string;
  readonly appealed: boolean;
  readonly award_milli?: number;
  readonly decided_at?: string;
  readonly defenses: number;
  readonly escrow_ref: string;
  readonly expires_at: string;
  readonly key: string;
  readonly kind: string;
  readonly notices: ReadonlyArray<PrivateCaseNotice>;
  readonly object: string;
  readonly opened_at?: string;
  readonly role: string;
  readonly status: string;
  readonly title: string;
  readonly value_milli: number;
  readonly verdict?: string;
  readonly version: number;
}

export interface PrivateCaseNotice {
  readonly event: string;
  readonly title: string;
}

export interface PrivateCaseRuling {
  readonly appeal_due_at: string;
  readonly appealed: boolean;
  readonly award_milli: number;
  readonly decided_at: string;
  readonly decision_code: string;
  readonly key: string;
  readonly terms_hash: string;
  readonly title: string;
  readonly verdict: string;
}
