// Code generated by tools/contractgen from internal/metering/adapters/http/openapi.fragment.json. DO NOT EDIT.
// Source of truth: internal/metering/adapters/http/openapi.fragment.json (staged fragment, not part of the published contract).
// Readonly by convention: every emitted member is readonly.
// HTTP surface SHA-256: 510c4b9264ef4d0469eead60e2df20fa500359011cc58a45aecb0dd331985558

export interface MeteringLeg {
  readonly amount_milli: number;
  readonly direction: string;
  readonly kind: string;
  readonly label: string;
}

export interface MeteringPublication {
  readonly posted_at: string;
  readonly publication_id: string;
  readonly replayed: boolean;
  readonly title: string;
  readonly total_milli: number;
  readonly transfer_id: string;
}

export interface MeteringQuote {
  readonly accepted_at: string;
  readonly content_hash: string;
  readonly expires_at: string;
  readonly price_milli: number;
  readonly quote_hash: string;
  readonly title: string;
  readonly total_milli: number;
  readonly units: number;
  readonly version: number;
}

export interface MeteringReceipt {
  readonly content_hash: string;
  readonly legs: ReadonlyArray<MeteringLeg>;
  readonly posted_at: string;
  readonly publication_id: string;
  readonly refund?: MeteringRefund;
  readonly service: string;
  readonly title: string;
  readonly total_milli: number;
  readonly transfer_id: string;
  readonly units: number;
  readonly version: number;
}

export interface MeteringRefund {
  readonly amount_milli: number;
  readonly posted_at: string;
  readonly refund_id: string;
  readonly transfer_id: string;
}

export interface MeteringStatement {
  readonly balance_milli: number;
  readonly entries: ReadonlyArray<MeteringStatementEntry>;
  readonly title: string;
}

export interface MeteringStatementEntry {
  readonly posted_at: string;
  readonly publication_id: string;
  readonly refunded: boolean;
  readonly service: string;
  readonly total_milli: number;
}
