// Code generated by tools/contractgen from internal/seasons/adapters/http/openapi.fragment.json. DO NOT EDIT.
// Source of truth: internal/seasons/adapters/http/openapi.fragment.json (staged fragment, not part of the published contract).
// Readonly by convention: every emitted member is readonly.

export interface SeasonChampionLeader {
  readonly display: string;
  readonly subject: string;
}

export interface SeasonChampionsDocument {
  readonly cutoff_revision: number;
  readonly hash: string;
  readonly last_king: string;
  readonly last_king_title: string;
  readonly leaders: ReadonlyArray<SeasonChampionLeader>;
  readonly richest_title: string;
  readonly season_key: string;
  readonly title: string;
}

export interface SeasonDocument {
  readonly ends_at: string;
  readonly ordinal: number;
  readonly season_key: string;
  readonly starts_at: string;
  readonly state: string;
  readonly title: string;
}

export interface SeasonHistoryDocument {
  readonly seasons: ReadonlyArray<SeasonDocument>;
  readonly title: string;
}
