#!/usr/bin/env bash
# Negative role tests for Regnovum (P03-T03).
#
# Proves, against the real development database, that each role is denied
# exactly the actions the role model forbids (docs/ROLE_MODEL.md). A probe
# that succeeds — or fails for the WRONG reason (bad password, missing
# database) — fails the battery. Positive controls first prove each role
# can connect and read its legitimate surface, so a negative result can
# only mean "denied by grants", never "could not run the test".
#
# Usage: scripts/dev-roles-negative-tests.sh
# Environment:
#   ARENA_DEV_APP_PASSWORD            password of arena_app (login role)
#   ARENA_DEV_BACKUP_PASSWORD         password of arena_backup
#   ARENA_DEV_OBSERVABILITY_PASSWORD  password of arena_observability
set -uo pipefail

# Admin connections run INSIDE the compose service (docker compose exec):
# the database is reachable at localhost:5432 there. Role probes also run
# in-container, authenticating with each role's own password.
ADMIN_URL="${ARENA_DEV_DB_URL:-postgres://arena:arena-local-dev@localhost:5432/arena?sslmode=disable}"
SCRATCH_DB="arena_roles_negative_probe"
ADMIN_QUERY="${ADMIN_URL#*\?}"		# query part: everything after the FIRST "?"
ADMIN_BASE="${ADMIN_URL%\?*}"		# base part: everything before the first "?"
SCRATCH_URL="${ADMIN_BASE%/*}/$SCRATCH_DB?$ADMIN_QUERY"

failures=0

# The admin URL always points at the "arena" database. Build the scratch
# URL from it by dropping the query (everything from the FIRST literal
# "?"), keeping the base, and re-appending the query. Escaped \? is the
# literal question mark; an unescaped ? in a bash glob matches ANY
# character (it once ate the "//arena:" of the scheme).
psql_url() {
	local url="$1"
	shift
	docker compose exec -T db psql "$url" "$@"
}

psql_admin() {
	psql_url "$ADMIN_URL" "$@"
}

psql_role() {
	local role="$1" password="$2" database="$3"
	shift 3
	docker compose exec -T db env PGPASSWORD="$password" psql \
		"postgres://$role@localhost:5432/$database?sslmode=disable" "$@"
}

require_env() {
	local variable="$1"
	if [ -z "${!variable:-}" ]; then
		echo "missing environment variable $variable (export the role passwords first)" >&2
		exit 64
	fi
}

# probe_must_fail runs SQL as a role inside the scratch database and
# requires failure with the expected denial reason. Wrong-reason failures
# (authentication, missing database, syntax) are battery errors.
probe_must_fail() {
	local label="$1" role="$2" password="$3" sql="$4"
	local output
	output="$(psql_role "$role" "$password" "$SCRATCH_DB" -v ON_ERROR_STOP=1 -t -A -c "$sql" 2>&1)"
	local status=$?
	if [ $status -eq 0 ]; then
		echo "FAIL: $label (probe unexpectedly succeeded)"
		failures=$((failures + 1))
	elif grep -q "permission denied\|must be owner" <<<"$output"; then
		echo "ok:   $label"
	else
		echo "FAIL: $label (failed for the wrong reason): $output"
		failures=$((failures + 1))
	fi
}

# control_must_pass proves the role can execute legitimate SQL; it keeps
# the negative probes honest.
control_must_pass() {
	local label="$1" role="$2" password="$3" sql="$4"
	if ! psql_role "$role" "$password" "$SCRATCH_DB" -v ON_ERROR_STOP=1 -t -A -c "$sql" >/dev/null 2>&1; then
		echo "FAIL: $label (positive control failed)"
		failures=$((failures + 1))
	else
		echo "ok:   $label"
	fi
}

for variable in ARENA_DEV_APP_PASSWORD ARENA_DEV_BACKUP_PASSWORD ARENA_DEV_OBSERVABILITY_PASSWORD; do
	require_env "$variable"
done

cleanup() {
	psql_admin -q -c "DROP DATABASE IF EXISTS $SCRATCH_DB;" >/dev/null 2>&1 || true
}
trap cleanup EXIT

# Build the scratch database with the same shape migration 00001/00003
# produce. Setup failures abort the battery (set -u plus explicit checks):
# an unprobed scratch database would make every negative probe vacuous.
cleanup
psql_admin -q -v ON_ERROR_STOP=1 -c "CREATE DATABASE $SCRATCH_DB;" >/dev/null || {
	echo "setup failed: cannot create scratch database" >&2
	exit 1
}
psql_url "$SCRATCH_URL" -q -v ON_ERROR_STOP=1 \
	-c "CREATE SCHEMA IF NOT EXISTS app;" \
	-c "CREATE TABLE IF NOT EXISTS app.schema_metadata (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, version_id bigint NOT NULL, is_applied boolean NOT NULL, tstamp timestamp NOT NULL DEFAULT now());" \
	-c "ALTER SCHEMA app OWNER TO arena_owner;" \
	-c "ALTER TABLE app.schema_metadata OWNER TO arena_owner;" \
	-c "GRANT CONNECT ON DATABASE $SCRATCH_DB TO arena_app, arena_backup, arena_observability;" \
	-c "GRANT USAGE ON SCHEMA app TO arena_app, arena_backup, arena_observability;" \
	-c "GRANT SELECT ON app.schema_metadata TO arena_app, arena_backup, arena_observability;" \
	>/dev/null || {
	echo "setup failed: cannot shape scratch database" >&2
	exit 1
}

# Prove the shaping landed in the SCRATCH database: the version table must
# exist and be readable through the scratch connection itself.
if ! psql_url "$SCRATCH_URL" -t -A -c "SELECT 1 FROM app.schema_metadata LIMIT 1;" >/dev/null 2>&1; then
	echo "setup failed: scratch database was not shaped (shaping landed elsewhere?)" >&2
	exit 1
fi

APP_PASSWORD="$ARENA_DEV_APP_PASSWORD"
BACKUP_PASSWORD="$ARENA_DEV_BACKUP_PASSWORD"
OBS_PASSWORD="$ARENA_DEV_OBSERVABILITY_PASSWORD"

echo "=== positive controls ==="
control_must_pass "runtime CAN read the migration history" arena_app "$APP_PASSWORD" \
	"SELECT count(*) FROM app.schema_metadata;"
control_must_pass "backup CAN read the app schema" arena_backup "$BACKUP_PASSWORD" \
	"SELECT count(*) FROM app.schema_metadata;"
control_must_pass "observability CAN read catalogs" arena_observability "$OBS_PASSWORD" \
	"SELECT count(*) FROM pg_stat_activity;"

echo "=== negative probes ==="
probe_must_fail "runtime cannot CREATE TABLE in app" arena_app "$APP_PASSWORD" \
	"CREATE TABLE app.app_forbidden (id integer);"
probe_must_fail "runtime cannot CREATE SCHEMA" arena_app "$APP_PASSWORD" \
	"CREATE SCHEMA app2;"
probe_must_fail "runtime cannot UPDATE the migration history" arena_app "$APP_PASSWORD" \
	"UPDATE app.schema_metadata SET is_applied = false;"
probe_must_fail "runtime cannot DELETE the migration history" arena_app "$APP_PASSWORD" \
	"DELETE FROM app.schema_metadata;"
probe_must_fail "runtime cannot DROP the migration history" arena_app "$APP_PASSWORD" \
	"DROP TABLE app.schema_metadata;"
probe_must_fail "runtime cannot CREATE ROLE" arena_app "$APP_PASSWORD" \
	"CREATE ROLE sneaky LOGIN;"
probe_must_fail "backup cannot INSERT" arena_backup "$BACKUP_PASSWORD" \
	"INSERT INTO app.schema_metadata (version_id, is_applied) VALUES (1, true);"
probe_must_fail "observability cannot INSERT" arena_observability "$OBS_PASSWORD" \
	"INSERT INTO app.schema_metadata (version_id, is_applied) VALUES (1, true);"

if [ "$failures" -gt 0 ]; then
	echo "negative-test battery: $failures FAILURE(S)"
	exit 1
fi
echo "negative-test battery: all controls and probes behaved as expected"
